python/vegafusion-jupyter/vegafusion_jupyter/widget.py
vegafusion-wasm/src/lib.rs

Two small updates to how messages are exchanged between client and server:
1. Client should not send a task graph query to the server if no nodes need updating (if the request indices is empty)
2. The server (vegafusion-jupyter in this case) shouldn't manually clear the message prop after sending a response. This was causing dropped messages in certain situations.

Message passing refinements

---

vegafusion-core/src/expression/escape.rs
vegafusion-core/src/expression/mod.rs
vegafusion-core/src/planning/projection_pushdown.rs
vegafusion-core/src/planning/split_domain_data.rs
vegafusion-core/src/spec/scale.rs
vegafusion-core/src/spec/visitors.rs
vegafusion-rt-datafusion/tests/specs/custom/escaped_column_name1.comm_plan.json
vegafusion-rt-datafusion/tests/specs/custom/escaped_column_name1.vg.json
vegafusion-rt-datafusion/tests/specs/custom/layered_movies.comm_plan.json
vegafusion-rt-datafusion/tests/specs/custom/layered_movies.vg.json
vegafusion-rt-datafusion/tests/test_image_comparison.rs

This PR adds two additional test mocks with associated fixes. Details to follow
This mock tests handling of columns that contain quote characters, making sure that the escape semantics match Vega.
This mock previously hit an error `Unrecognized signal name: "layer_1_bin_step_5_tomatometer_rating_bins"`. This was caused by a previously unsupported structure of a scale domain specification.
```json
"domain": {
"fields": [
{
"signal": "[layer_0_bin_step_5_audience_rating_bins.start, layer_0_bin_step_5_audience_rating_bins.stop]"
},
{
"signal": "[layer_1_bin_step_5_tomatometer_rating_bins.start, layer_1_bin_step_5_tomatometer_rating_bins.stop]"
}
]
```

Add additional test mocks

---

Cargo.lock
python/vegafusion/tests/test_pretransform.py
vegafusion-core/src/data/dataset.rs
vegafusion-core/src/data/mod.rs
vegafusion-core/src/spec/chart.rs
vegafusion-core/src/spec/visitors.rs
vegafusion-python-embed/Cargo.toml
vegafusion-python-embed/src/lib.rs
vegafusion-rt-datafusion/benches/spec_benchmarks.rs
vegafusion-rt-datafusion/src/data/dataset.rs
vegafusion-rt-datafusion/src/data/mod.rs
vegafusion-rt-datafusion/src/data/tasks.rs
vegafusion-rt-datafusion/src/signal/mod.rs
vegafusion-rt-datafusion/src/task_graph/runtime.rs
vegafusion-rt-datafusion/src/task_graph/task.rs
vegafusion-rt-datafusion/tests/test_image_comparison.rs
vegafusion-rt-datafusion/tests/test_planning.rs
vegafusion-rt-datafusion/tests/test_task_graph_runtime.rs
vegafusion-server/tests/test_task_graph_runtime.rs
vegafusion-wasm/src/lib.rs

This PR fixes an issue introduced in https://github.com/vegafusion/vegafusion/pull/124.  This PR changed how inline datasets to `pre_transform_spec` are processed, and unintentionally resulted in these datasets being cached based only on their name (not their value).  This means that the inline dataset used internally was not updated when the input dataset changes across repeated calls.
This PR addresses the issue, in introducing a few new concepts:
- The value of the data `url` property may now optionally end with a `#{fingerprint}` suffix. This fingerprint is part of the task's hash, but is ignored by the runtime when actually processing the URL.
- A new `VegaFusionDataset` abstraction was added that represents a dataset that has a fingerprint and can be turned into a DataFrame. For …

Fix invalid dataset caching in pre_transform_spec

---

vegafusion-core/src/planning/stringify_local_datetimes.rs
vegafusion-rt-datafusion/src/expression/compiler/builtin_functions/date_time/datetime.rs
vegafusion-rt-datafusion/tests/test_stringify_datetimes.rs

Followup fix for https://github.com/vegafusion/vegafusion/pull/128

Fix for stringify local datetimes with ordinal scale

---

vegafusion-core/src/spec/transform/stack.rs
vegafusion-rt-datafusion/src/transform/formula.rs
vegafusion-rt-datafusion/src/transform/stack.rs
vegafusion-rt-datafusion/tests/specs/custom/stacked_bar_normalize.comm_plan.json
vegafusion-rt-datafusion/tests/specs/vegalite/rect_mosaic_labelled.comm_plan.json
vegafusion-rt-datafusion/tests/specs/vegalite/rect_mosaic_simple.comm_plan.json
vegafusion-rt-datafusion/tests/specs/vegalite/stacked_bar_h_normalized_labeled.comm_plan.json
vegafusion-rt-datafusion/tests/specs/vegalite/stacked_bar_normalize.comm_plan.json
vegafusion-rt-datafusion/tests/specs/vegalite/stacked_bar_population_transform.comm_plan.json
vegafusion-rt-datafusion/tests/test_transform_stack.rs

This PR is a follow-on to https://github.com/vegafusion/vegafusion/pull/137 that adds support for performing the `stack` transform with `offset` values of `"center"` and `"normalize"`.

Add support for stack transform with normalize and center offsets

---

javascript/vegafusion-embed/package-lock.json
python/vegafusion/tests/test_pretransform.py
python/vegafusion/vegafusion/runtime.py
vegafusion-core/src/error.rs
vegafusion-core/src/proto/pretransform.proto
vegafusion-core/src/proto/prost_gen/pretransform.rs
vegafusion-core/src/proto/prost_gen/services.rs
vegafusion-core/src/proto/services.proto
vegafusion-core/src/proto/tonic_gen/pretransform.rs
vegafusion-core/src/proto/tonic_gen/services.rs
vegafusion-core/src/spec/data.rs
vegafusion-python-embed/src/lib.rs
vegafusion-rt-datafusion/src/task_graph/runtime.rs
vegafusion-rt-datafusion/tests/test_image_comparison.rs
vegafusion-rt-datafusion/tests/test_pre_transform_values.rs
vegafusion-rt-datafusion/tests/test_stringify_datetimes.rs
vegafusion-server/src/main.rs

This PR adds a new high-level method to the Python `Runtime` called `pre_transform_datasets`.  Docstring:
```
Extract the fully evaluated form of the requested datasets from a Vega specification
as pandas DataFrames.
:param spec: A Vega specification
:param datasets: A list with elements that are either:
- The name of a top-level dataset as a string
- A two-element tuple where the first element is the name of a dataset as a string
and the second element is the nested scope of the dataset as a list of integers
:param local_tz: Name of timezone to be considered local. E.g. 'America/New_York'.
This can be computed for the local system using the tzlocal package and the
tzlocal.get_localzone_name() function.
:param default_input_tz: Name of timezone (e.g. 'America/New_York') that naive …
```

Add pre_transform_datasets functionality

---

vegafusion-core/src/proto/prost_gen/transforms.rs
vegafusion-core/src/proto/tonic_gen/transforms.rs
vegafusion-core/src/proto/transforms.proto
vegafusion-core/src/spec/transform/impute.rs
vegafusion-core/src/spec/transform/mod.rs
vegafusion-core/src/spec/transform/unsupported.rs
vegafusion-core/src/transform/impute.rs
vegafusion-core/src/transform/mod.rs
vegafusion-rt-datafusion/src/transform/impute.rs
vegafusion-rt-datafusion/src/transform/mod.rs
vegafusion-rt-datafusion/tests/specs/vegalite/area_gradient.comm_plan.json
vegafusion-rt-datafusion/tests/specs/vegalite/area_overlay.comm_plan.json
vegafusion-rt-datafusion/tests/specs/vegalite/interactive_legend.comm_plan.json
vegafusion-rt-datafusion/tests/specs/vegalite/interactive_legend_dblclick.comm_plan.json
vegafusion-rt-datafusion/tests/specs/vegalite/interactive_overview_detail.comm_plan.json
vegafusion-rt-datafusion/tests/specs/vegalite/stacked_area.comm_plan.json
vegafusion-rt-datafusion/tests/specs/vegalite/stacked_area_normalize.comm_plan.json
vegafusion-rt-datafusion/tests/specs/vegalite/stacked_area_ordinal.comm_plan.json
vegafusion-rt-datafusion/tests/specs/vegalite/stacked_area_overlay.comm_plan.json
vegafusion-rt-datafusion/tests/specs/vegalite/stacked_area_stream.comm_plan.json
vegafusion-rt-datafusion/tests/test_transform_impute.rs

This PR adds support for evaluating certain configurations of the Vega [`impute`](https://vega.github.io/vega/docs/transforms/impute/) transform in the VegaFusion Runtime.  This initial implementation aims to support Vega-Lite's use of `impute` when generating stacked area charts.
This implementation only supports the following subset of the functionality of `impute`
- `method` must be 'value'
- `groupby` must be a list of zero or one field.
Other uses of impute are detected and the planner pushes them into the client specification

Add initial impute transform support

---

python/vegafusion/tests/test_pretransform.py
vegafusion-core/src/planning/extract.rs
vegafusion-core/src/planning/plan.rs
vegafusion-rt-datafusion/tests/test_planning.rs

Adds a new warning that gets returned by `pre_transform_spec` when not all transforms for a dataset can be pre-evaluated.

Add planner warning to pre_transform_spec when unsupported transforms are found

---

vegafusion-core/src/spec/transform/timeunit.rs
vegafusion-rt-datafusion/src/expression/compiler/call.rs
vegafusion-rt-datafusion/src/sql/connection/datafusion_conn.rs
vegafusion-rt-datafusion/src/transform/timeunit.rs
vegafusion-rt-datafusion/tests/test_image_comparison.rs

This PR restores support for `week` and `dayofyear` time units.  This was unintentionally dropped during the great SQL refactor.
This is done by reintroducing the legacy timeunit logic as a fallback DataFusion UDF.

Restore support for Week and DayOfYear TimeUnits

---

python/vegafusion/tests/test_input_utc.py
vegafusion-rt-datafusion/src/data/tasks.rs
vegafusion-rt-datafusion/src/expression/compiler/builtin_functions/date_time/timestamp_to_timestamptz.rs

This PR fixes a regression, likely introduced by the SQL refactor, where a coercion error was raised when a chart inputs a Timestamp column that includes an explicit timezone.
The test in [python/vegafusion/tests/test_input_utc.py](https://github.com/vegafusion/vegafusion/compare/jonmmease/fix_input_tz?expand=1#diff-d39023213e058cef50ff5e7620616ed4e30289c82176e9eb283719c5480d00c3) reproduces the initial error.

Fix regression for timestamps with explicit timezones

---

python/vegafusion/tests/test_pretransform.py
vegafusion-rt-datafusion/src/data/tasks.rs
vegafusion-rt-datafusion/tests/specs/inline_datasets/period_in_field_name.vg.json
vegafusion-rt-datafusion/tests/test_pre_transform_values.rs

This is a follow-on fix to https://github.com/vegafusion/vegafusion/pull/167 that handles the case where a dataset with dot-containing field names is provided as an inline dataset.
Rust and Python tests are included

Fix for inline dataset with dots in field names

---

vegafusion-rt-datafusion/src/transform/aggregate.rs
vegafusion-rt-datafusion/tests/specs/custom/pivot_crash.comm_plan.json
vegafusion-rt-datafusion/tests/specs/custom/pivot_crash.vg.json
vegafusion-rt-datafusion/tests/test_image_comparison.rs

Currently, when a specified aggregation column does not exist, VegaFusion panics.  Vega allows this case using the following rules:
- Sum and Count on non-existent column is 0
- All other aggregate ops result in null/undefined
This PR bring VegaFusion in line with Vega in this situation

Match Vega's behavior when an aggregate column does not exist

---

vegafusion-core/src/planning/stringify_local_datetimes.rs
vegafusion-rt-datafusion/tests/specs/pre_transform/stocks_layered_pivot_bug.vg.json
vegafusion-rt-datafusion/tests/test_stringify_datetimes.rs

This PR updates the `stringify_local_datetimes` planner phase to correctly identify local datetime usage in faceted marks.  
The test spec in [tests/specs/pre_transform/stocks_layered_pivot_bug.vg.json](https://github.com/vegafusion/vegafusion/compare/jonmmease/pivot_error?expand=1#diff-3b3d09c98a3972170271ae1afded754a2d351163c4a738f9bb1658d042f716d1) is an example of a spec where this came up.

Update stringify_local_datetimes planner to handle faceted marks

---

python/vegafusion/tests/test_pretransform.py
vegafusion-rt-datafusion/src/expression/compiler/builtin_functions/date_time/timestamp_to_timestamptz.rs
vegafusion-rt-datafusion/src/expression/compiler/builtin_functions/date_time/timestamptz_to_timestamp.rs

Small change to handle null Timestamp values.
Issue: The arrow `unary` function can be used to map a unary function across a primitive array, propagating the nulls mask. The docs for `unary` state that the function must be infallible because it will be evaluated with whatever happens to be stored in the data array for null values.  The issue is that `timestamp_to_timestamptz` UDF performs a timezone conversion, and so it is not valid for arbitrary i32 array elements.
Solution: Switch to using `array.iter().map()` to map over boxed `Optional` array element values. This way we only perform the timezone conversions on valid timestamp values.

Handle null Timestamp values

---

vegafusion-rt-datafusion/src/transform/pivot.rs
vegafusion-rt-datafusion/tests/specs/custom/sorted_pivot_lines.comm_plan.json
vegafusion-rt-datafusion/tests/specs/custom/sorted_pivot_lines.vg.json
vegafusion-rt-datafusion/tests/test_image_comparison.rs

This PR fixes a crash for a pivot transform of the form:
```json
{
"type": "pivot",
"field": "MPAA Rating",
"value": "US Gross",
"groupby": ["Release Date"]
}
```
Where the pivot field has a space in the name

Fix crash in pivot transform for column with spaces

---

vegafusion-rt-datafusion/src/expression/compiler/builtin_functions/data/vl_selection_test.rs
vegafusion-rt-datafusion/src/task_graph/runtime.rs
vegafusion-rt-datafusion/tests/specs/custom/stacked_bar_initial_selection.comm_plan.json
vegafusion-rt-datafusion/tests/specs/custom/stacked_bar_initial_selection.vg.json
vegafusion-rt-datafusion/tests/test_image_comparison.rs

Copy inline JSON datasets directly to pre-transform output specs, instead of round-tripping through Arrow.
Consider a stacked bar chart in Vega-Lite with a point selection to control the bar opacity:
```json
{
"$schema": "https://vega.github.io/schema/vega-lite/v5.json",
"data": {
"values": [
{"number": 1, "group": "x", "value":0.1},
{"number": 1, "group": "y", "value":0.6},
{"number": 1, "group": "z", "value":0.9},
{"number": 2, "group": "x", "value":0.7},
{"number": 2, "group": "y", "value":0.2},
{"number": 2, "group": "z", "value":1.1},
{"number": 3, "group": "x", "value":0.6},
{"number": 3, "group": "y", "value":0.1},
{"number": 3, "group": "z", "value":0.2}
]
},
"params": [
{
"name": "click",
"value": [
{"number": 2, "group": "x"},
{"number": 3, "group": "z"},
],
"select": {
"type": …
```

Copy inline JSON datasets directly to pre-transform output specs

---

vegafusion-rt-datafusion/src/lib.rs
vegafusion-rt-datafusion/src/pre_transform/destringify_selection_datetimes.rs
vegafusion-rt-datafusion/src/pre_transform/mod.rs
vegafusion-rt-datafusion/src/task_graph/runtime.rs
vegafusion-rt-datafusion/tests/specs/pre_transform/datetime_strings_in_selection_stores.vg.json
vegafusion-rt-datafusion/tests/test_destringify_selection_datasets.rs

This PR adds support to pre_transform_spec for handling Vega-Lite style selection store datasets that include datetime string.
Point selection example:
```json
{
"name": "click_store",
"values": [
{
"unit": "",
"fields": [
{"field": "yearmonth_date", "channel": "x", "type": "E"},
{"field": "weather", "channel": "color", "type": "E"}
],
"values": ["2014-01-01T00:00:00", "sun"]
},
{
"unit": "",
"fields": [
{"field": "yearmonth_date", "channel": "x", "type": "E"},
{"field": "weather", "channel": "color", "type": "E"}
],
"values": ["2013-11-01T00:00:00", "rain"]
}
]
},
```
Interval selection example:
```json
{
"name": "drag_store",
"values": [
{
"unit": "",
"fields": [{"field": "yearmonth_date", "channel": "x", "type": "R"}],
"values": [["2012-11-27T06:58:03.000", "2013-06-04T06:38:51.000"]] …
```

Update pre_transform_spec to handle selection datasets with datetime strings

---

vegafusion-rt-datafusion/src/expression/compiler/builtin_functions/data/data_fn.rs
vegafusion-rt-datafusion/src/expression/compiler/builtin_functions/data/vl_selection_resolve.rs
vegafusion-rt-datafusion/src/expression/compiler/builtin_functions/data/vl_selection_test.rs
vegafusion-rt-datafusion/src/expression/compiler/call.rs
vegafusion-rt-datafusion/tests/specs/pre_transform/datetime_strings_in_selection_stores.vg.json
vegafusion-rt-datafusion/tests/test_destringify_selection_datasets.rs
vegafusion-rt-datafusion/tests/test_pre_transform_values.rs
vegafusion-rt-datafusion/tests/test_selection.rs

This PR updates the implementation of VlSelectionTest to support comparison values (either enum values for a point selection or range values for an interval selection) as datetime strings.
Combined with https://github.com/vegafusion/vegafusion/pull/182, this makes it possible for a full `pre_transform_spec` workflow to support datetime strings in selection stores, whether the selection is used on the server the client or both.

Add support for VlSelectionTest for providing comparison scalars as datetime strings

---

vegafusion-rt-datafusion/src/transform/pivot.rs
vegafusion-rt-datafusion/tests/test_transform_pivot.rs

This PR updates the `pivot` transform to use the names `"true"` and `"false"` rather than 1 and 0 for boolean columns.  
Previously, we were casting all non-string column values to strings, but casting a boolean to a string in DataFusion results in 0/1 as column names.  Now booleans are handled separately to produce "true"/"false" column names.

Fix column names for boolean pivot field

---

Cargo.lock
vegafusion-core/Cargo.toml
vegafusion-core/src/spec/transform/aggregate.rs
vegafusion-core/src/spec/transform/joinaggregate.rs
vegafusion-core/src/spec/visitors.rs
vegafusion-rt-datafusion/Cargo.toml
vegafusion-rt-datafusion/src/data/tasks.rs
vegafusion-rt-datafusion/src/transform/aggregate.rs
vegafusion-rt-datafusion/src/transform/joinaggregate.rs
vegafusion-rt-datafusion/tests/specs/vega/barley.comm_plan.json
vegafusion-rt-datafusion/tests/specs/vega/layout-wrap.comm_plan.json
vegafusion-rt-datafusion/tests/specs/vegalite/concat_weather.comm_plan.json
vegafusion-rt-datafusion/tests/specs/vegalite/line_slope.comm_plan.json
vegafusion-rt-datafusion/tests/specs/vegalite/trellis_barley.comm_plan.json
vegafusion-rt-datafusion/tests/specs/vegalite/trellis_barley_independent.comm_plan.json
vegafusion-rt-datafusion/tests/specs/vegalite/trellis_barley_layer_median.comm_plan.json
vegafusion-rt-datafusion/tests/test_image_comparison.rs
vegafusion-rt-datafusion/tests/test_transform_aggregate.rs
vegafusion-rt-datafusion/tests/util/datasets.rs

This PR adds support for evaluating median aggregations in VegaFusion.
This is done by buiding VegaFusion against a custom branch of DataFusion. This branch is based on DataFusion 15 (the last official release) with a [median bug fix](https://github.com/apache/arrow-datafusion/pull/4488) cherry picked on top of it.
As an aside, going forward I think it makes sense to stick to using major version releases of DataFusion, with any specific bug fixes we need cherry picked on top.
----
Separately, to help with some test flakiness update the data tasks to retry get requests using [`reqwest_retry`](https://docs.rs/reqwest-retry/latest/reqwest_retry/).

Add median support

---

python/vegafusion/tests/test_pretransform.py
vegafusion-core/src/planning/dependency_graph.rs
vegafusion-core/src/planning/extract.rs
vegafusion-core/src/planning/plan.rs
vegafusion-core/src/planning/stringify_local_datetimes.rs
vegafusion-core/src/planning/unsupported_data_warning.rs
vegafusion-core/src/spec/data.rs
vegafusion-core/src/spec/transform/aggregate.rs
vegafusion-core/src/spec/transform/bin.rs
vegafusion-core/src/spec/transform/collect.rs
vegafusion-core/src/spec/transform/extent.rs
vegafusion-core/src/spec/transform/filter.rs
vegafusion-core/src/spec/transform/formula.rs
vegafusion-core/src/spec/transform/identifier.rs
vegafusion-core/src/spec/transform/impute.rs
vegafusion-core/src/spec/transform/joinaggregate.rs
vegafusion-core/src/spec/transform/lookup.rs
vegafusion-core/src/spec/transform/mod.rs
vegafusion-core/src/spec/transform/pivot.rs
vegafusion-core/src/spec/transform/project.rs
vegafusion-core/src/spec/transform/sequence.rs
vegafusion-core/src/spec/transform/stack.rs
vegafusion-core/src/spec/transform/timeunit.rs
vegafusion-core/src/spec/transform/window.rs
vegafusion-rt-datafusion/src/expression/compiler/builtin_functions/date_time/date_format.rs
vegafusion-rt-datafusion/src/expression/compiler/builtin_functions/date_time/datetime.rs
vegafusion-rt-datafusion/src/task_graph/runtime.rs
vegafusion-rt-datafusion/tests/specs/pre_transform/interactive_average.vg.json
vegafusion-rt-datafusion/tests/test_stringify_datetimes.rs

This PR updates the `pre_transform_spec` logic to avoid breaking interactivity in the output chart specs.
Previously, `pre_transform_spec` the same planning approach as `VegaFusionWidget`. This approach extracts all supported data transforms into the server specification and then computes which datasets and signals must be transferred to and from the client to maintain interactivity.  This is what we want for `VegaFusionWidget`, but not for `pre_transform_spec`.
The output of `pre_transform_spec` is designed to be rendered by a regular (non-VegaFusion aware) Vega renderer, so there is no way to perform client-to-server communications.  Instead, what we want is for the planner to extract as much as possible for evaluation on the server without introducing any client-to-server communication …

Maintain interactivity of chart specifications produced by pre_transform_spec

---

Cargo.lock
python/vegafusion/tests/test_input_utc.py
python/vegafusion/tests/test_pretransform.py
python/vegafusion/vegafusion/runtime.py
vegafusion-python-embed/Cargo.toml
vegafusion-python-embed/src/lib.rs
vegafusion-rt-datafusion/src/task_graph/runtime.rs
vegafusion-rt-datafusion/tests/test_destringify_selection_datasets.rs
vegafusion-rt-datafusion/tests/test_pre_transform_values.rs
vegafusion-rt-datafusion/tests/test_stringify_datetimes.rs

Small API update to reduce JSON serialization by having the pre_transform_* functions input and return objects rather than strings.
In Rust this means inputting and returning ChartSpec objects instead of strings
In Python this means inputting and returning dicts instead of strings.

Update the pre_transform_* API to input and return JSON objects instead of strings

---

.github/workflows/build_test.yml

Run python tests on the development build of vegafusion-python-embed. This way the Python tests don't need to wait for all of the vegafusion-python-embed wheels to build
Also split the building of macos arm wheels into a separate CI job so that the mac build doesn't take extra long.

CI speedups

---

python/vegafusion-jupyter/tests/test_conext_manager.py
python/vegafusion-jupyter/vegafusion_jupyter/__init__.py
python/vegafusion-jupyter/vegafusion_jupyter/widget.py
python/vegafusion/tests/test_conext_manager.py
python/vegafusion/vegafusion/__init__.py
python/vegafusion/vegafusion/utils.py

Closes https://github.com/vegafusion/vegafusion/issues/200
Adds support for enabling and disabling VegaFusion renderers/data transformers in context managers.
The following now work as you would expect:
```python
from IPython.display import display
with vf.enable_mime():
display(chart)
with vf.disable():
display(chart)
with vf.enable_widget():
display(chart)
```
cc @mattijn

Support enabling/disabling VegaFusion renderers as context managers

---

python/vegafusion-jupyter/tests/test_conext_manager.py
python/vegafusion/tests/test_conext_manager.py
python/vegafusion/vegafusion/__init__.py
python/vegafusion/vegafusion/renderer.py

This PR changes the default mimetype from `"html"` to `"vega"`. While `"html"` works in both the classic notebook and JupyterLab, it requires an active internet connection .  The `"vega"` type works in JupyterLab, Visual Studio Code, nteract, and other modern environments and does not require an internet connection.
It also adds (html-)colab and (html-)kaggle mime types that follow Altair's logic for supporting display in Colab and Kaggle notebooks.

Change default mime type to "vega", add Colab and Kaggle support

---

vegafusion-core/src/expression/supported.rs
vegafusion-rt-datafusion/src/expression/compiler/call.rs
vegafusion-rt-datafusion/tests/specs/custom/sin_cos.comm_plan.json
vegafusion-rt-datafusion/tests/specs/custom/sin_cos.vg.json
vegafusion-rt-datafusion/tests/test_image_comparison.rs

The `sin` expression function was missing, so this PR adds it.

Add missing sin expression function

---

python/vegafusion/tests/test_conext_manager.py
python/vegafusion/tests/test_row_limit.py
python/vegafusion/vegafusion/__init__.py
python/vegafusion/vegafusion/renderer.py

This PR adds a new `row_limit` argument to the `vf.enable_mime()` function that is used to specify the maximum number of rows (after transforms are applied) that are allowed to be inlined into the Vega specification that will be sent to the client.  
```python
import vegafusion as vf
vf.enable_mime(row_limit=10000)
...
chart
```
The default limit is 10,000
Like Altair's built-in RowLimit, this is to protect users from accidentally crashing their browser. But unlike regular Altair, this limit is enforced after the Chart's transforms have been applied.  The error message advises users that they can get around the error by introducing an aggregation or raising the `row_limit` argument to the `enable_mime` function.

Add configurable row limit for mime renderer

---

python/vegafusion/tests/test_conext_manager.py
python/vegafusion/vegafusion/__init__.py
python/vegafusion/vegafusion/renderer.py

This PR changes the default mime renderer mimetype to "html".
This is consistent with Altair's default, and so should be less surprising for users who have never had to think about mimetypes.

Default renderer back to "html" for consistency with Altair

---

python/vegafusion/tests/test_pretransform.py
python/vegafusion/tests/test_transformed_data.py
python/vegafusion/vegafusion/runtime.py

Previously datetime columns returned by `vf.transformed_data` were naive but implicitly in the UTC timezone.  This PR localizes them as UTC then converts them to VegaFusion's local timezone.
For example:
```python
import vegafusion as vf
from vega_datasets import data
vf.set_local_tz("America/Los_Angeles")
source = data.seattle_weather()
chart = alt.Chart(source).mark_bar(
cornerRadiusTopLeft=3,
cornerRadiusTopRight=3
).encode(
x='month(date):O',
y='count():Q',
color='weather:N'
)
chart
```
```python
tx_df = vf.transformed_data(chart, row_limit=5)
tx_df
```
|    | weather   | month_date                |   __count |   __count_start |   __count_end |
|---:|:----------|:--------------------------|----------:|----------------:|--------------:|
|  0 | drizzle   | …

Localize/convert transformed_data datetimes to local_tz

---

python/vegafusion-jupyter/tests/test_altair_mocks.py
python/vegafusion/tests/test_conext_manager.py
python/vegafusion/tests/test_row_limit.py
python/vegafusion/vegafusion/__init__.py
python/vegafusion/vegafusion/renderer.py

This PR renames the `vf.enable_mime()` function to simply `vf.enable()`.
This is to remove an early point of confusion for users who aren't familiar with the term mime(type).  There is still a `mimetype` argument to the function, but it will default to `html` so a user isn't forced to deal with it in most cases.
The `enable_widget()` function stays as is.  I considered merging it into `vf.enable()`, but the widget renderer has several distinct configuration options that would complicate the signature of `vf.enable` with options that are only valid for the widget renderer.

Rename enable_mime() to enable()

---

Cargo.lock
Cargo.toml
vegafusion-core/Cargo.toml
vegafusion-rt-datafusion/Cargo.toml
vegafusion-rt-datafusion/tests/test_transform_aggregate.rs
vegafusion-rt-datafusion/tests/util/check.rs

This fixes PR fixes the following errors with aggregating a column with nulls using the `distinct` aggregation operation
```
PanicException: Failed to get node value: DataFusionError(ArrowError(ExternalError(ArrowError(ExternalError(Internal("Unexpected accumulator state List([NULL])"))))), ErrorContext { contexts: [] })
```
```
InvalidArgumentError("Column 'COUNT(DISTINCT tbl.col2)[count distinct]' is declared as non-nullable but contains null values")
```
The root cause was an issue in `arrow-rs`: https://github.com/apache/arrow-rs/issues/3471. Also, see the DataFusion issue: https://github.com/apache/arrow-datafusion/issues/4828.
Proposed fix in arrow was opened in https://github.com/apache/arrow-rs/pull/3473.
To take advantage of the fix immediately, I created a custom branch based on …

Fix distinct aggregation with nulls

---

Cargo.lock
Cargo.toml
python/vegafusion/vegafusion/transformer.py
vegafusion-core/src/data/mod.rs
vegafusion-core/src/data/table.rs
vegafusion-core/src/spec/transform/impute.rs
vegafusion-rt-datafusion/src/data/tasks.rs
vegafusion-rt-datafusion/src/transform/aggregate.rs
vegafusion-rt-datafusion/src/transform/collect.rs
vegafusion-rt-datafusion/src/transform/identifier.rs
vegafusion-rt-datafusion/src/transform/impute.rs
vegafusion-rt-datafusion/src/transform/joinaggregate.rs
vegafusion-rt-datafusion/src/transform/pipeline.rs
vegafusion-rt-datafusion/src/transform/pivot.rs
vegafusion-rt-datafusion/src/transform/project.rs
vegafusion-rt-datafusion/src/transform/stack.rs
vegafusion-rt-datafusion/src/transform/window.rs
vegafusion-rt-datafusion/tests/specs/custom/area_streamgraph.comm_plan.json
vegafusion-rt-datafusion/tests/specs/custom/area_streamgraph.vg.json
vegafusion-rt-datafusion/tests/specs/vegalite/stacked_bar_h_order_custom.vg.json
vegafusion-rt-datafusion/tests/test_image_comparison.rs
vegafusion-rt-datafusion/tests/test_transform_aggregate.rs
vegafusion-rt-datafusion/tests/test_transform_identifier.rs
vegafusion-rt-datafusion/tests/test_transform_impute.rs
vegafusion-rt-datafusion/tests/test_transform_window.rs
vegafusion-rt-datafusion/tests/util/check.rs
vegafusion-rt-datafusion/tests/util/equality.rs

Unlike SQL, The row order of the result of Vega transforms is deterministic based on the transform specification and the order of the input rows.  For example, the rows that result from the `aggregate` transform are ordered according to first appearance of a row in each group.
Prior to this PR, we attempted to match Vega's ordering by having individual transforms use a ROW_NUMBER() window function on their input, and the resort their output based on this ROW_NUMBER().  This worked most of the time, but it was a bit of a hack since creating a new column using a ROW_NUMBER window function, and no ordering specification, isn't guaranteed to be sorted with the input rows.
Here is one example where this approach goes wrong: https://github.com/apache/arrow-datafusion/issues/4673.
This PR …

Improve transform ordering using explicit ordering column

---

python/vegafusion/tests/test_transformed_data.py
python/vegafusion/vegafusion/evaluation.py
vegafusion-core/src/spec/transform/impute.rs
vegafusion-rt-datafusion/src/transform/impute.rs
vegafusion-rt-datafusion/tests/specs/custom/ridgeline.comm_plan.json
vegafusion-rt-datafusion/tests/test_transform_impute.rs
vegafusion-rt-datafusion/tests/util/equality.rs

This PR adds support for the `impute` transform with more than one `groupby` field.  It also updates the `transfored_data` Python function to handle `FacetChart` instances

Support impute with multiple groupby fields and match Vega's output ordering

---

README.md
javascript/vegafusion-embed/package.json
javascript/vegafusion-embed/package/package.json
python/vegafusion-jupyter/package.json
python/vegafusion/setup.cfg
vegafusion-wasm/README.md
vegafusion-wasm/package.json

Updates various project links now that the VegaFusion repos have moved under the `hex-inc` GitHub org

Update repo links for move to hex-inc org

---

python/vegafusion/vegafusion/__init__.py
python/vegafusion/vegafusion/evaluation.py

Adds forward compatibility with Altair 5 (which is not yet released)

Add forward compatibility with Altair 5

---

vegafusion-core/src/expression/escape.rs
vegafusion-core/src/spec/transform/aggregate.rs
vegafusion-core/src/spec/transform/bin.rs
vegafusion-core/src/spec/transform/collect.rs
vegafusion-core/src/spec/transform/extent.rs
vegafusion-core/src/spec/transform/fold.rs
vegafusion-core/src/spec/transform/impute.rs
vegafusion-core/src/spec/transform/joinaggregate.rs
vegafusion-core/src/spec/transform/lookup.rs
vegafusion-core/src/spec/transform/pivot.rs
vegafusion-core/src/spec/transform/project.rs
vegafusion-core/src/spec/transform/stack.rs
vegafusion-core/src/spec/transform/timeunit.rs
vegafusion-core/src/spec/transform/window.rs
vegafusion-rt-datafusion/tests/specs/custom/special_chars_bar.comm_plan.json
vegafusion-rt-datafusion/tests/specs/custom/special_chars_bar.vg.json
vegafusion-rt-datafusion/tests/test_image_comparison.rs

This PR adds a previously failing test in e7e8d2ad7170237654630c925a429f5fdde59045. The issue is that projection pushdown was creating a transform that looked like this:
```json
{
"type": "project",
"fields": ["pe.riod", "pe\\.riod"]
}
```
The resulting error was:
```
Projections require unique expression names but the expression \"tbl_1.pe.riods\" at position 1 and \"tbl_1.pe.riods\" at position 2 have the same name
```
To fix the issue, 81f5aef85c61b4967e64945ddd2d62978b46cb0d updates the `transform_columns` transform spec implementations to unescape fields before including them in `ColumnUsage` sets. 
4794951e007565ef1e39c404361992a5ad760f59 updates the (un)escape logic to handle periods and brackets.

Handle special characters in projection pushdown

---

vegafusion-datafusion-udfs/src/udfs/datetime/date_add_tz.rs
vegafusion-datafusion-udfs/src/udfs/datetime/date_part_tz.rs
vegafusion-datafusion-udfs/src/udfs/datetime/date_trunc_tz.rs
vegafusion-datafusion-udfs/src/udfs/datetime/format_timestamp.rs
vegafusion-datafusion-udfs/src/udfs/datetime/from_utc_timestamp.rs
vegafusion-datafusion-udfs/src/udfs/datetime/to_utc_timestamp.rs
vegafusion-datafusion-udfs/src/udfs/datetime/utc_timestamp_to_epoch.rs
vegafusion-datafusion-udfs/src/udfs/datetime/utc_timestamp_to_str.rs
vegafusion-runtime/src/expression/compiler/builtin_functions/date_time/date_format.rs
vegafusion-runtime/src/expression/compiler/builtin_functions/date_time/date_parts.rs
vegafusion-runtime/src/expression/compiler/builtin_functions/date_time/time.rs
vegafusion-sql/src/dialect/mod.rs

DataFusion won't automatically cast from timestamp nanos to timestamp millis due to precision loss. Therefore all of our timestamp UDFs should accept timestamp nanos, and perform the conversion internally if necessary.

All timestamp UDFs should accept nanoseconds / Date32 / Date64

---

python/vegafusion/vegafusion/connection/duckdb.py
vegafusion-sql/src/dialect/transforms/to_utc_timestamp.rs

Follow up to https://github.com/hex-inc/vegafusion/pull/252.
When a chart references an external duckdb table (using a "table://{name}" URL string), we were caching the table's schema the first time it was accessed. But when working interactively, this table's schema may change.
After this PR, we only cache the schema of tables directly registered with the VegaFusion DuckDBConnection.

Don't cache DuckDB schema of externally registered tables

---

javascript/vegafusion-embed/package-lock.json
python/vegafusion-jupyter/package-lock.json
vegafusion-common/src/data/table.rs
vegafusion-core/src/spec/chart.rs
vegafusion-core/src/spec/visitors.rs
vegafusion-datafusion-udfs/src/udfs/array/span.rs
vegafusion-datafusion-udfs/src/udfs/object/mod.rs
vegafusion-runtime/src/expression/compiler/mod.rs
vegafusion-runtime/src/transform/bin.rs
vegafusion-runtime/src/transform/sequence.rs
vegafusion-runtime/tests/specs/custom/taxi_dashboard.comm_plan.json
vegafusion-runtime/tests/specs/custom/taxi_dashboard.vg.json
vegafusion-runtime/tests/test_expression_evaluation.rs
vegafusion-runtime/tests/test_image_comparison.rs
vegafusion-runtime/tests/util/vegajs_runtime/vegajsRuntime.js
vegafusion-wasm/js/vega_utils.js
vegafusion-wasm/src/lib.rs

I'm working on a new version of the [NYC Taxi Dashboard](https://vegafusion.io/example_nyc_taxi.html) example.  To improve the experience of zooming in on the pickup location view, I want to bind the bin extent to the axis scale. e.g.
```python
pickup_chart = base.mark_rect().encode(
x=alt.X(
"pickup_x:Q",
bin=alt.Bin(maxbins=width_bins, extent=scales),
scale=alt.Scale(domain=x_domain),
),
...
)
```
This small change uncovered a whole slew of issues, mostly related to signals that have an initial state of `undefined`.
Here's a full example, based on the new DuckDB connection with an external DuckDB table:
```python
import duckdb
import vegafusion as vf
conn = duckdb.connect()
vf.runtime.set_connection(conn)
rel = conn.read_parquet("./nyc_taxi.parquet") …
```

Various fixes to support updated Taxi Dashboard example

---

python/vegafusion/vegafusion/runtime.py
vegafusion-common/src/data/table.rs
vegafusion-python-embed/src/connection.rs
vegafusion-python-embed/src/lib.rs

This PR re-enables the use of the zero-copy interface between pyarrow and arrow-rs.
The test that was added previously that failed with the use of the zero-copy interface is now passing, and everything worked fine when using it for the DuckDB integration.
Closes #125

Re-enable zero copy from pyarrow to arrow-rs

---

.github/workflows/build_test.yml
python/vegafusion-jupyter/package-lock.json
python/vegafusion-jupyter/package.json
python/vegafusion/tests/altair_mocks/interactive/casestudy-us_population_over_time/mock.py

Updates the version of Vega-Lite that's bundled with VegaFusionWidget to 4.6.1, which matches Altair 5.0.0rc1.  Use Altair 5.0.0rc1 in tests.

Update Vega and Vega-Lite in VegaFusionWidget

---

python/vegafusion/tests/test_pretransform.py
python/vegafusion/vegafusion/runtime.py
vegafusion-python-embed/src/lib.rs

Closes https://github.com/hex-inc/vegafusion/issues/268
This fixes / works around the hang reported in #268. I don't understand the full cause, but it's mitigated by copying the input Arrow table through the IPC format.  We lose zero copy, but it should still be an improvement over prior versions as the IPC clone is happening all in Rust. Also important, this approach allows us to compute an accurate hash for the input table (rather than using the Python `id` of the PyArrow table), so it improves cacheing.

Fix 1.1.0rc4 hang in pre_transform_dataset

---

python/vegafusion/tests/test_pretransform.py
python/vegafusion/vegafusion/runtime.py
vegafusion-common/src/data/json_writer.rs

Updates `pre_transform_datasets` (and thereby `vf.transformed_data`) to output polars DataFrame(s) if:
- There is at least one inline dataset
- all of the inline datasets are polars DataFrames
This way a polars user can create a chart from a polars DataFrame and retrieve a polars DataFrame with `vf.transformed_data` all without any pandas conversions.

Output polars/arrow from pre_transform_datasets/transformed_data

---

javascript/vegafusion-embed/package-lock.json
python/vegafusion-jupyter/package-lock.json
vegafusion-wasm/src/lib.rs

Adds several public Vega View methods to the `MsgReceiver` WASM struct:
```
pub fn get_signal(&self, name: &str, scope: &[u32]) -> JsValue ;
pub fn get_data(&self, name: &str, scope: &[u32]) -> JsValue;
pub fn set_signal(&self, name: &str, scope: &[u32], value: JsValue);
pub fn set_data(&self, name: &str, scope: &[u32], value: JsValue);
pub fn get_state(&self) -> JsValue;
pub fn set_state(&self, state: JsValue);
pub fn run(&self);
pub fn run_async(&self) -> Promise;
```
These are to make it easier to introspect and manipulate the view from outside.

Expose WASM methods for getting and setting signal and data values

---

vegafusion-runtime/src/expression/compiler/builtin_functions/data/vl_selection_test.rs
vegafusion-runtime/tests/test_selection.rs

Fix a crash when a Vega spec contains an initial selection like this:
```json
[
{
"unit": "",
"fields": [
{"field": "Major Genre", "channel": "x", "type": "E"},
{"field": "is_pg", "channel": "color", "type": "E"}
],
"values": ["Adventure", true]
},
{
"unit": "",
"fields": [
{"field": "Major Genre", "channel": "x", "type": "E"},
{"field": "is_pg", "channel": "color", "type": "E"}
],
"values": ["Comedy", false]
}
]
```
When converting to arrow, the `true` and `false` scalars get converted to the string `"true"` and `"false"`, which resulted in the following error in `vlSelectionTest`.
```
'Boolean = Utf8' can't be evaluated because there isn't a common type to coerce the types to
```
This fixes the crash, by converting the strings "true" and "false" back to booleans when a string is …

Fix crash when initial selection contains mix of string and bool

---

Cargo.lock
javascript/vegafusion-chart-editor/index.js
javascript/vegafusion-chart-editor/package-lock.json
javascript/vegafusion-embed/package-lock.json
javascript/vegafusion-embed/package.json
vegafusion-core/Cargo.toml
vegafusion-server/Cargo.toml
vegafusion-server/src/main.rs
vegafusion-wasm/Cargo.toml

This PR fixes the chart editor demo in `javascript/vegafusion-chart-editor`
This is a simple example of a Vega chart editor that uses `vegafusion-embed` in the client to display the Vega chart, [perform planning](https://vegafusion.io/how_it_works.html#planner), and communicate with an instance of the [vegafusion-server](https://github.com/hex-inc/vegafusion/tree/main/vegafusion-server) over gRPC-Web.
I needed to update tonic-web to the latest git revision to fix a CORS issue. I also needed to update the `getrandom` crate to fix an annoying webpack warning.
https://user-images.githubusercontent.com/15064365/227393558-f6418de2-3633-46a6-b2e6-a9552964245f.mov

Fix chart editor demo project

---

.github/workflows/build_test.yml

Merged https://github.com/hex-inc/vegafusion/pull/277 too quickly.  The path of the apple silicon build is under a different release directory.

Fix path to apple silicon build of vegafusion-server

---

python/vegafusion/tests/test_pretransform_specs.py
python/vegafusion/vegafusion/runtime.py
vegafusion-core/src/planning/watch.rs
vegafusion-core/src/proto/pretransform.proto
vegafusion-core/src/proto/prost_gen/pretransform.rs
vegafusion-core/src/proto/prost_gen/services.rs
vegafusion-core/src/proto/services.proto
vegafusion-core/src/proto/tonic_gen/pretransform.rs
vegafusion-core/src/proto/tonic_gen/services.rs
vegafusion-python-embed/src/lib.rs
vegafusion-runtime/src/task_graph/runtime.rs
vegafusion-runtime/tests/test_image_comparison.rs
vegafusion-runtime/tests/test_pre_transform_extract.rs
vegafusion-runtime/tests/test_vegajs_runtime.rs
vegafusion-server/src/main.rs

This PR adds a new low-level api (alongside `pre_transform_spec` and `pre_transform_dataset`) called `pre_transform_extract`.  
The `pre_transform_spec` function evaluates the transforms in an input spec and inlines the results into the resulting transformed JSON specification. This makes the resulting spec self-contained (able to be rendered directly by the Vega JavaScript library) , but for non-aggregated charts this can result in a really large JSON spec and cost a lot in terms of serialization.
The new `pre_transform_extract` function works like `pre_transform_spec`, but only datasets of under 21 rows are inlined into the resulting transformed JSON spec. Larger datasets are returned separately in arrow format.  Each extracted dataset is a tuple of `(name, scope, table)`.
The …

Add pre_transform_extract low-level API

---

python/vegafusion/tests/test_transformed_data.py
python/vegafusion/vegafusion/runtime.py
vegafusion-runtime/src/data/tasks.rs

Closes #286 by casting LargeUtf8 to Utf8. This change can be reverted if/when https://github.com/apache/arrow-rs/issues/2654 is fixed/
Also threw in a fix for pre_transform_dataset when inputting and Arrow table

Work around LargeUtf8 to Utf8 comparison error

---

python/vegafusion/tests/test_save.py
python/vegafusion/vegafusion/__init__.py
python/vegafusion/vegafusion/renderer.py
python/vegafusion/vegafusion/save.py

Closes https://github.com/hex-inc/vegafusion/issues/292
This PR adds a set of new top-level functions for saving Altair charts to files after applying VegaFusion's `pre_transform_spec` logic. This is the exact same logic that is applied in the [Mime Renderer](https://vegafusion.io/mime_renderer.html) before charts are displayed in a notebook environment.  The functions are:
- save_html
- save_vega
- save_png
- save_svg
Here's an example of saving a 1 million row histogram to HTML with Altair directly (using the `Chart.save` function):
```python
import pandas as pd
import vegafusion as vf
vf.enable()
flights = pd.read_parquet(
"https://vegafusion-datasets.s3.amazonaws.com/vega/flights_1m.parquet"
)
delay_hist = alt.Chart(flights).mark_bar().encode(
alt.X("delay", …
```

Add save functions

---

python/vegafusion/tests/test_transformed_data.py
python/vegafusion/vegafusion/connection/duckdb.py

This PR updates the DuckDB connection to convert categorical columns to strings rather than ignoring them.  The new test in `python/vegafusion/tests/test_transformed_data.py` now works.
```python
@pytest.mark.parametrize("connection", get_connections())
def test_categorical_columns(connection):
vf.runtime.set_connection(connection)
df = pd.DataFrame({
"a": [0, 1, 2, 3, 4, 5],
"categorical": pd.Categorical.from_codes([0, 1, 0, 1, 1, 0], ["A", "BB"])
})
chart = alt.Chart(df).mark_bar().encode(
alt.X("categorical:N"), alt.Y("sum(a):Q")
)
transformed = vf.transformed_data(chart)
expected = pd.DataFrame({"categorical": ["A", "BB"], "sum_a": [7, 8]})
pd.testing.assert_frame_equal(transformed, expected)
```

Handle categorical columns with DuckDB connection

---

Cargo.lock
javascript/vegafusion-embed/package-lock.json
javascript/vegafusion-embed/package.json
python/vegafusion-jupyter/package-lock.json
vegafusion-core/Cargo.toml
vegafusion-python-embed/Cargo.toml
vegafusion-runtime/tests/util/vegajs_runtime/package-lock.json
vegafusion-server/Cargo.toml
vegafusion-server/src/main.rs
vegafusion-wasm/Cargo.toml
vegafusion-wasm/package-lock.json
vegafusion-wasm/src/lib.rs

Updates tonic/tonic-web to 0.9.1 to no longer depend on git revision. This means we'll be able to publish vegafusion-server to crates.io again.
Also updates other Rust and JS dependencies

Update tonic/tonic-web and other dependencies

---

python/vegafusion/tests/altair_mocks/interactive/casestudy-seattle_weather_interactive/mock.py
python/vegafusion/tests/altair_mocks/interactive/casestudy-us_population_pyramid_over_time/mock.py
python/vegafusion/tests/altair_mocks/interactive/cross_highlight/mock.py
python/vegafusion/tests/altair_mocks/interactive/multiline_highlight/mock.py
python/vegafusion/tests/altair_mocks/interactive/multiline_tooltip/mock.py
python/vegafusion/tests/altair_mocks/interactive/scatter-with_linked_table/mock.py
python/vegafusion/tests/altair_mocks/interactive/scatter-with_minimap/mock.py
python/vegafusion/tests/altair_mocks/interactive/scatter_with_histogram/mock.py
python/vegafusion/tests/altair_mocks/interactive/scatter_with_layered_histogram/mock.py
python/vegafusion/tests/altair_mocks/interactive/select_mark_area/mock.py
python/vegafusion/tests/altair_mocks/interactive/selection_histogram/mock.py
python/vegafusion/tests/altair_mocks/interactive/selection_layer_bar_month/mock.py
python/vegafusion/tests/altair_mocks/scatter/dot_dash_plot/mock.py
python/vegafusion/tests/test_transformed_data.py
python/vegafusion/vegafusion/evaluation.py

Closes #307
Extends the `transformed_data` function to support extract transformed datasets from compound charts. In this case, a list of DataFrames is returned, one for each non-excluded subchart.
Logic is tested against all of the compound charts in the chart mock library.

Support transformed_data for Layered and Concatenated charts 

---

.github/workflows/build_test.yml
python/vegafusion-jupyter/package-lock.json
python/vegafusion-jupyter/package.json

Update vega dependency versions to match Altair 5.0.0
- vega to 0.25.0
- vega-lite to 5.8.0
- vega-embed to 2.13.0

Update VegaFusionWidget's Vega deps to match Altair 5.0.0

---

python/vegafusion/tests/test_pretransform.py
vegafusion-sql/src/dataframe/mod.rs
vegafusion-sql/src/dialect/mod.rs

This PR provides a fix for the situation where the `pivot` transform produces multiple columns that differ only by case (e.g. `red` and `Red`) when using a DuckDB connection. DuckDB doesn't support tables with mixed case identical columns, so here we detect this situation and fall back to using the DataFusion connection in these cases.
Test added in 8579a217f2e9721011596db26b9e8327576c26de

Fix crash when pivot produces columns that differ only by case with DuckDB backend

---

java/lib/src/main/java/io/vegafusion/VegaFusionRuntime.java
java/lib/src/test/java/io/vegafusion/VegaFusionRuntimeTest.java
vegafusion-core/src/spec/chart.rs
vegafusion-jni/src/lib.rs

A few updates to the new Java API for the first release.
- preTransformSpec now returns a string containing the new Vega spec with the warnings included under `usermeta.vegafusion_warnings`.
- `valid` renamed to `isValid`
- `validate` exposed as a public method

Java API updates

---

.github/workflows/java.yml

Previously, the JNI libs were being built with GitHub Actions `ubuntu-latest` which is currently Ubuntu `22.04`. This results in a GLIB_C requirement of `2.35` so the shared libs won't work on older Ubuntu versions. This drops the required GLIBC version to `2.31`
This PR downgrades the linux CI images to 20.04 for improved compatibility.

Build JNI libs on Ubuntu 20.04 for older GLIBC

---

java/lib/src/main/java/io/vegafusion/VegaFusionRuntime.java
java/lib/src/test/java/io/vegafusion/VegaFusionRuntimeTest.java
vegafusion-jni/src/lib.rs

Add `numThreads` argument to the VegaFusionRuntime Java constructor. This controls the number of threads in the embedded tokio runtime.

Add Java arg for number of worker threads

---

python/vegafusion/tests/test_transformed_data.py
vegafusion-core/src/spec/transform/aggregate.rs
vegafusion-core/src/spec/transform/joinaggregate.rs
vegafusion-core/src/spec/transform/window.rs
vegafusion-core/src/transform/aggregate.rs
vegafusion-core/src/transform/joinaggregate.rs
vegafusion-datafusion-udfs/src/lib.rs
vegafusion-datafusion-udfs/src/udafs/mod.rs
vegafusion-runtime/src/transform/aggregate.rs
vegafusion-runtime/tests/specs/vegalite/boxplot_1D_horizontal.comm_plan.json
vegafusion-runtime/tests/specs/vegalite/boxplot_1D_horizontal_custom_mark.comm_plan.json
vegafusion-runtime/tests/specs/vegalite/boxplot_1D_horizontal_explicit.comm_plan.json
vegafusion-runtime/tests/specs/vegalite/boxplot_1D_vertical.comm_plan.json
vegafusion-runtime/tests/specs/vegalite/boxplot_2D_horizontal.comm_plan.json
vegafusion-runtime/tests/specs/vegalite/boxplot_2D_horizontal_color_size.comm_plan.json
vegafusion-runtime/tests/specs/vegalite/boxplot_2D_vertical.comm_plan.json
vegafusion-runtime/tests/specs/vegalite/boxplot_groupped.comm_plan.json
vegafusion-runtime/tests/specs/vegalite/boxplot_minmax_2D_horizontal.comm_plan.json
vegafusion-runtime/tests/specs/vegalite/boxplot_minmax_2D_horizontal_custom_midtick_color.comm_plan.json
vegafusion-runtime/tests/specs/vegalite/boxplot_minmax_2D_vertical.comm_plan.json
vegafusion-runtime/tests/specs/vegalite/boxplot_tooltip_aggregate.comm_plan.json
vegafusion-runtime/tests/specs/vegalite/boxplot_tooltip_not_aggregate.comm_plan.json
vegafusion-runtime/tests/specs/vegalite/layer_boxplot_circle.comm_plan.json
vegafusion-runtime/tests/specs/vegalite/layer_point_errorbar_2d_horizontal_iqr.comm_plan.json
vegafusion-runtime/tests/test_transform_aggregate.rs
vegafusion-sql/src/connection/datafusion_conn.rs
vegafusion-sql/src/dialect/mod.rs

This PR adds implementations of the Vega q1 and q3 aggregations using a custom DataFusion UDAF.
If VegaFusion eventually supports the `percentile_cont` aggregation function, then this UDF could be replaced.
As one common application, this makes it possible for VegaFusion to support all of the data transformations associated with the Vega-Lite [`boxplot` mark](https://vega.github.io/vega-lite/docs/boxplot.html).

Add q1 and q3 aggregations

---

python/vegafusion/tests/test_pretransform.py
python/vegafusion/vegafusion/runtime.py
vegafusion-core/src/lib.rs
vegafusion-core/src/planning/plan.rs
vegafusion-core/src/planning/stitch.rs
vegafusion-core/src/proto/pretransform.proto
vegafusion-core/src/proto/prost_gen/pretransform.rs
vegafusion-core/src/proto/tonic_gen/pretransform.rs
vegafusion-jni/src/lib.rs
vegafusion-python-embed/src/lib.rs
vegafusion-runtime/src/task_graph/runtime.rs
vegafusion-runtime/tests/specs/pre_transform/manual_histogram.vg.json
vegafusion-runtime/tests/test_destringify_selection_datasets.rs
vegafusion-runtime/tests/test_image_comparison.rs
vegafusion-runtime/tests/test_planning.rs
vegafusion-runtime/tests/test_pre_transform_keep_variables.rs
vegafusion-runtime/tests/test_stringify_datetimes.rs

This PR adds the ability to keep select signals and datasets in the result of pre_transform_spec. By default, signals and datasets are not included if they are not required by the pre-transformed spec. But sometimes, it's helpful to have them included anyway.
A motivating use case is the `bin` transform's output signal. Sometimes this signals is used only by the transform pipeline itself and so is not required in the pre_transformed spec.  Even when it's not required, it can be helpful for the calling system to have access to the bin edge specification.
See the new Rust and Python tests for usage examples

Support keeping select signals and datasets in pre-transformed specs

---

vegafusion-sql/src/compile/expr.rs
vegafusion-sql/src/dialect/mod.rs
vegafusion-sql/tests/expected/select_window.toml
vegafusion-sql/tests/test_window.rs

Many SQL dialects (including DataFusion and DuckDB) allow the use of the `ROW_NUMBER` window function without an explicit `ORDER BY` clause: 
```sql
SELECT ROW_NUMBER() OVER () FROM tbl
```
But some (including Snowflake and Databricks) do not. For Snowflake, we can substitute the [`seq8` function](https://docs.snowflake.com/en/sql-reference/functions/seq1):
```sql
SELECT seq8() FROM tbl
```
I haven't found an equivalent for Databricks, so in this case we can add a constant ordering value
```sql
SELECT ROW_NUMBER() OVER (ORDER BY 1) FROM tbl
```
cc @FreddieLindsey

Add dialect specialization for the row_number window function without ordering

---

.github/workflows/README.md
.github/workflows/build.yml
.github/workflows/build_test.yml
.github/workflows/java.yml
.github/workflows/semgrep.yml
vegafusion-core/src/task_graph/graph.rs

Add linux arm64 builds of `vegafusion-server` and the `vegafusion-python-embed` wheel. 
Refactor CI jobs to pull out build.yml, which contains artifact building for vegafusion-server and vegafusion-python-embed.
Finally, addresses semgrep warning by pinning the hash of the GitHub actions versions

Add linux-arm64 builds

---

python/vegafusion/vegafusion/dataset/duckdb.py
python/vegafusion/vegafusion/dataset/sql.py

The `dialect` method of the abstract `SqlDataset` class can be a regular method, rather than a classmethod.
This increases flexibility and allows SqlDataset subclasses to dynamically determine their dialect.

SqlDataset.dialect doesn't have to be a classmethod

---

python/vegafusion/tests/test_sql_dataset.py
python/vegafusion/vegafusion/dataset/dfi.py
python/vegafusion/vegafusion/dataset/duckdb.py
python/vegafusion/vegafusion/dataset/sql.py

Updates the `SqlDataset.__dataframe__` method to support introspecting column schema info without evaluating the underlying SQL query. Combined with Altair dev, this will make it possible to pass SqlDataset instances into Altair for column type inference without triggering the SQL query.
Heavily inspired by https://github.com/ibis-project/ibis/pull/6733

Add lazy implementation of DataFrame Interchange Protocol to SqlDataset

---

Cargo.lock
python/vegafusion/vegafusion/dataset/snowpark.py
vegafusion-sql/Cargo.toml
vegafusion-sql/src/compile/scalar.rs
vegafusion-sql/src/dataframe/mod.rs
vegafusion-sql/src/dialect/mod.rs
vegafusion-sql/src/dialect/transforms/date_to_utc_timestamp.rs
vegafusion-sql/tests/expected/select.toml
vegafusion-sql/tests/test_select.rs
vegafusion-sql/tests/utils/mod.rs

This PR adds an initial Python `SnowparkDataset` implementation that derives from `SqlDataset`. It uses the `snowflake` SQL dialect and evaluates queries using [snowflake-snowpark-python](https://pypi.org/project/snowflake-snowpark-python/).
Here is some example usage with Altair using:
- Altair 5.1.0 dev from git
- snowflake-connector-python==3.1.0a2 (This version doesn't pin pyarrow)
- pyarrow 12
```python
from vegafusion.dataset.snowpark import SnowparkDataset
from snowflake.snowpark import Session, Table
connection_parameters = {
"account": "<your snowflake account>",
"user": "<your snowflake user>",
"password": "<your snowflake password>",
"role": "<snowflake user role>",
"warehouse": "<snowflake warehouse>",
"database": "<snowflake database>",
"schema": …
```

Add SnowparkDataset and date_to_utc_timestamp support across dialects

---

.github/workflows/build_test.yml
vegafusion-common/src/datatypes.rs
vegafusion-core/src/planning/stringify_local_datetimes.rs
vegafusion-runtime/src/expression/compiler/mod.rs
vegafusion-sql/src/compile/expr.rs
vegafusion-sql/src/dialect/mod.rs
vegafusion-sql/tests/expected/select.toml
vegafusion-sql/tests/test_select.rs

This PR adds support for the TRY_CAST construct across SQL dialects and switches to using TRY_CAST for type conversions. This avoids crashes for things like Vega's `toNumeric("abc")`, instead returning a NULL, which is much closer to Vega's behavior (it returns a NaN).
Also adds an explicit `toDate` to the local datetime stringification logic to handle edge cases where a string column is used in a local datetime context without conversion.

Fix edge cases: Use TRY_CAST for type conversions, convert cols to datetime before stringification

---

.github/workflows/build_test.yml

We should be able to unpin `vl-convert-python` now that https://github.com/vega/vl-convert/issues/94 was fixed in  `vl-convert-python` 0.13.1.

Unpin vl-convert-python now that 0.13.1 is out

---

vegafusion-core/src/planning/projection_pushdown.rs
vegafusion-core/src/planning/split_domain_data.rs
vegafusion-core/src/planning/stringify_local_datetimes.rs
vegafusion-core/src/spec/scale.rs
vegafusion-core/src/spec/visitors.rs
vegafusion-runtime/tests/specs/custom/gh_383.comm_plan.json
vegafusion-runtime/tests/specs/custom/gh_383.vg.json
vegafusion-runtime/tests/test_image_comparison.rs

Fixes https://github.com/hex-inc/vegafusion/issues/382 by allowing `scale.domain.fields` array to contain a mix of data references and signals.
e.g.
```json
[
{
"signal": "[concat_0_bin_maxbins_20_mean_price_bins.start, concat_0_bin_maxbins_20_mean_price_bins.stop]"
},
{
"signal": "[concat_1_layer_0_bin_maxbins_20_mean_price_bins.start, concat_1_layer_0_bin_maxbins_20_mean_price_bins.stop]"
},
{
"data": "source_2",
"field": "mean_price"
}
]
```
I didn't know Vega-Lite would do this, and apparently Vega supports it.
Closes https://github.com/hex-inc/vegafusion/issues/382

Allow scale.domain.fields to contain signals

---

python/vegafusion/vegafusion/dataset/dataframe.py
python/vegafusion/vegafusion/dataset/sql.py
vegafusion-python-embed/src/lib.rs

Previously we forced the use of a single-threaded tokio runtime whenever a Python Datasource was in use. This was done to work around deadlocks, but has the unfortunate side affect of disabling multi-threaded parallelization of queries in these situations. This PR applies the technique discussed in See https://github.com/PyO3/pyo3/discussions/2182 to use the PyO3 `allow_threads` construct to release the Python GIL before performing blocking operations that may themselves need to acquire the GIL in separate threads.
In turns out that the DuckDbDatasource still requires running on the main thread in order to access the kernel's top-level DataFrames, so I made the main thread behavior configurable on a per-datasource level, where the default is to maintain the prior behavior of running on …

Free Python GIL on blocking operations to allow multi-threading runtime usage without deadlocks

---

vegafusion-core/src/planning/projection_pushdown.rs
vegafusion-core/src/planning/split_domain_data.rs
vegafusion-core/src/planning/stringify_local_datetimes.rs
vegafusion-core/src/spec/scale.rs
vegafusion-core/src/spec/visitors.rs
vegafusion-runtime/tests/specs/custom/gh_391.comm_plan.json
vegafusion-runtime/tests/specs/custom/gh_391.vg.json
vegafusion-runtime/tests/test_image_comparison.rs

Closes #391 
Handles scale domain data references of the form:
```json
"domain": {
"data": "data_2",
"fields": ["sum_value_start", "sum_value_end"]
}
```

Handle domain data reference with list of fields

---

vegafusion-core/src/patch.rs

In the patch pre-transformed spec logic, when a JSON object is replaced by an array, it could sometimes happen that the result would be an object with integer keys (e.g. `{"0": "A", "1": "BB"}` instead of an array (e.g. `["A", "BB"]`). I think this is a natural consequence of how JSON patching works, so I don't think it's necessarily a bug in json-patch.
This PR identifies such objects and converts them to proper arrays.

Fix patch_pre_transformed_spec when object is replaced by an array

---

.github/workflows/build_test.yml
vegafusion-core/src/planning/split_domain_data.rs
vegafusion-core/src/planning/stitch.rs

I came across a case where the VegaFusion planner paniced when passed a spec that contained unparsable Vega expression strings.  This removes that panic, and a couple of others in the vicinity.

Remove panics from planning logic

---

python/vegafusion/vegafusion/runtime.py
vegafusion-core/src/planning/dependency_graph.rs
vegafusion-core/src/planning/fuse.rs
vegafusion-core/src/planning/mod.rs
vegafusion-core/src/planning/plan.rs
vegafusion-core/src/spec/data.rs
vegafusion-python-embed/src/lib.rs
vegafusion-runtime/src/task_graph/runtime.rs
vegafusion-runtime/tests/test_projection_pushdown.rs

This PR updates the planner to combine (fuse) parent datasets into their children in certain situations.
The motivation here is to ensure that the root datasets in the server spec have more of the transform pipeline than previously.
A simple motivating example is that Vega-Lite can sometimes generate Vega specs where the root dataset has no transforms and then a child dataset has a series of transforms. For example:
```json
"data": [
{"name": "source_0", "url": "vegafusion+dataset://source"},
{
"name": "data_0",
"source": "source_0",
"transform": [
{
"type": "aggregate",
"groupby": ["A"],
"ops": ["average"],
"fields": ["B"],
}
]
},
]
```
Without these changes to the planner, VegaFusion will pull the entire `source_0` dataset into the runtime's cache. Then the `data_0` transforms are …

Add fuse_datasets planner configuration for combining datasets during planning

---

python/vegafusion/vegafusion/dataset/snowpark.py

Adds `safe=False` to the arrow table cast to allow casts that drop precision, like case form timestamp[ns] to timestamp[ms]

SnowparkDataset: Cast arrow table with safe=False to allow precision truncation

---

vegafusion-common/src/datatypes.rs
vegafusion-runtime/tests/test_transform_stack.rs
vegafusion-sql/src/dataframe/mod.rs

Fix error when using the stack transform on a timestamp column. We were failing to properly convert the column to integer milliseconds before stacking.

Fix cast timestamp to integer millisecond and add stack timestamp tests

---

vegafusion-core/src/expression/supported.rs
vegafusion-core/src/expression/visitors.rs
vegafusion-runtime/src/expression/compiler/builtin_functions/format.rs
vegafusion-runtime/src/expression/compiler/builtin_functions/mod.rs
vegafusion-runtime/src/expression/compiler/call.rs
vegafusion-runtime/src/transform/aggregate.rs
vegafusion-runtime/tests/specs/custom/binned_ordinal.comm_plan.json
vegafusion-runtime/tests/specs/custom/binned_ordinal.vg.json
vegafusion-runtime/tests/specs/vegalite/histogram_ordinal.comm_plan.json
vegafusion-runtime/tests/specs/vegalite/histogram_ordinal_sort.comm_plan.json
vegafusion-runtime/tests/test_image_comparison.rs
vegafusion-runtime/tests/test_transform_aggregate.rs
vegafusion-runtime/tests/test_transform_joinaggregate.rs
vegafusion-sql/src/dataframe/mod.rs

Closes #409 
Adds support for the `format` function when the format string argument is the empty string. In this case, numbers are converted to strings such that integer values in float columns are formatted without a decimal point.
While making a test case from the example in #409, I happened upon an unrelated issue. In the Vega aggregate/joinaggregate transforms, the `sum` aggregation returns zero if it inputs all null values. In SQL it returns null. I added a `coalesce` to replace these nulls with zeros.

Support format function with empty format string, make sum of nulls evaluate to zero

---

.github/workflows/build_test.yml
.github/workflows/java.yml
.gitignore
BUILD.md
Cargo.lock
Cargo.toml
automation/start_minio.py
pixi.lock
pixi.toml
vegafusion-common/Cargo.toml
vegafusion-common/src/error.rs
vegafusion-dataframe/src/connection.rs
vegafusion-runtime/Cargo.toml
vegafusion-runtime/src/data/tasks.rs
vegafusion-runtime/tests/test_pre_transform_values.rs
vegafusion-sql/Cargo.toml
vegafusion-sql/src/connection/datafusion_conn.rs

This PR adds initial support for loading input files from s3, and for parquet support. Includes:
- Use object_store::aws::AmazonS3Builder to support loading json, csv, arrow, and parquet files from s3. Credentials are pulled from environment variables per https://docs.rs/object_store/latest/object_store/aws/struct.AmazonS3Builder.html#method.from_env.
- Support loading parquet files from the local file system and from s3 (no support for http/https yet).
For testing, I added a pixi dependency on minio and added the `pixi start minio` task that start's minio with pre-determined credentials and loads sample data.

Experimental s3 and parquet support

---

vegafusion-core/src/planning/projection_pushdown.rs
vegafusion-core/src/planning/stitch.rs
vegafusion-core/src/spec/signal.rs
vegafusion-core/src/spec/values.rs
vegafusion-core/src/spec/visitors.rs
vegafusion-runtime/src/task_graph/runtime.rs

Closes #422, inspired by https://stackoverflow.com/questions/44331037/how-can-i-distinguish-between-a-deserialized-field-that-is-missing-and-one-that

Preserve null signal values on roundtrip (de)serialization

---

.github/workflows/build_test.yml
python/vegafusion/vegafusion/runtime.py
vegafusion-core/src/expression/visitors.rs
vegafusion-core/src/planning/plan.rs
vegafusion-core/src/proto/pretransform.proto
vegafusion-core/src/proto/prost_gen/pretransform.rs
vegafusion-core/src/proto/prost_gen/tasks.rs
vegafusion-core/src/proto/tasks.proto
vegafusion-core/src/proto/tonic_gen/pretransform.rs
vegafusion-core/src/proto/tonic_gen/tasks.rs
vegafusion-core/src/spec/values.rs
vegafusion-python-embed/src/lib.rs
vegafusion-runtime/benches/spec_benchmarks.rs
vegafusion-runtime/src/data/tasks.rs
vegafusion-runtime/src/expression/compiler/builtin_functions/format.rs
vegafusion-runtime/src/task_graph/runtime.rs
vegafusion-runtime/tests/test_chart_state.rs
vegafusion-runtime/tests/test_image_comparison.rs
vegafusion-server/src/main.rs
vegafusion-server/tests/test_task_graph_runtime.rs
vegafusion-sql/src/connection/datafusion_conn.rs
vegafusion-wasm/src/lib.rs

This PR adds a new `vf.runtime.new_chart_state` Python method which returns an instance of a `ChartState` Python class. The ChartState stores a copy of the TaskGraph that corresponds to the chart and provides an `update` method that can be used to update the task graph and return updates that should be made to the displayed visualization.
This is a step toward replacing `VegaFusionWidget` with Altair's own `JupyterChart`. My goal is that eventually the built-in Altair JuptyerChart will be able to optionally support VegaFusionWidget's current functionality. To accomplish this, JupyterChart will construct a ChartState and use it to determine what callbacks to install in the displayed Vega visualization, and will determine what properties to update in response to interactions.
A big …

Add ChartState for managing interactive chart state in Python

---

python/vegafusion/vegafusion/__init__.py
python/vegafusion/vegafusion/embed.py
python/vegafusion/vegafusion/jupyter.py
python/vegafusion/vegafusion/runtime.py
python/vegafusion/vegafusion/transformer.py
vegafusion-python-embed/src/lib.rs

Wraps the Rust ChartState pyo3 class in a pure Python wrapper that has a typed API.
Also removes some legacy (pre-1.0) copyright headers.

Wrap ChartState in pure Python class with typed API

---

vegafusion-core/src/planning/extract.rs
vegafusion-core/src/planning/stitch.rs
vegafusion-core/src/spec/signal.rs
vegafusion-core/src/spec/visitors.rs
vegafusion-runtime/tests/specs/custom/aggregate_with_threshold.comm_plan.json
vegafusion-runtime/tests/specs/custom/aggregate_with_threshold.updates.json
vegafusion-runtime/tests/specs/custom/aggregate_with_threshold.vg.json
vegafusion-runtime/tests/specs/vega/jobs.comm_plan.json
vegafusion-runtime/tests/specs/vega/layout-wrap.comm_plan.json
vegafusion-runtime/tests/specs/vega/population.comm_plan.json
vegafusion-runtime/tests/specs/vega/population.updates.json
vegafusion-runtime/tests/test_image_comparison.rs

Planner updates to support the dynamic threshold aggregation example described in https://github.com/altair-viz/altair/pull/3281#issuecomment-1858818046.
cc @mattijn

Support threshold aggregation example

---

Cargo.lock
python/vegafusion/tests/test_transformed_data.py
python/vegafusion/vegafusion/datasource/__init__.py
python/vegafusion/vegafusion/datasource/_dfi_types.py
python/vegafusion/vegafusion/datasource/datasource.py
python/vegafusion/vegafusion/datasource/dfi_datasource.py
python/vegafusion/vegafusion/datasource/pandas_datasource.py
python/vegafusion/vegafusion/runtime.py
vegafusion-dataframe/Cargo.toml
vegafusion-dataframe/src/connection.rs
vegafusion-python-embed/Cargo.toml
vegafusion-python-embed/src/lib.rs
vegafusion-sql/Cargo.toml
vegafusion-sql/src/connection/datafusion_conn.rs
vegafusion-sql/src/connection/datafusion_py_datasource.rs
vegafusion-sql/src/connection/mod.rs

Closes https://github.com/hex-inc/vegafusion/issues/386
This PR adds custom DataFusion datasources, written in Python, for pandas DataFrames and objects that adhere to the DataFrame Interchange Protocol (i.e. have a `__dataframe__` method). Using this approach, we no longer convert these objects directly to arrow before passing them into VegaFusion. Instead, they are converted to arrow dynamically during the DataFusion query. This makes it possible to down select to the required columns before converting to Arrow, which can be much much faster for DataFrames that include lots of columns.
Example of 10 million row histogram with pandas:
```python
import pandas as pd
alt.data_transformers.enable("vegafusion")
movies = …
```

Add DataFusion datasource implementation in Python for pandas and DataFrame Interchange

---

vegafusion-runtime/src/transform/aggregate.rs
vegafusion-runtime/tests/test_image_comparison.rs
vegafusion-runtime/tests/test_transform_aggregate.rs
vegafusion-runtime/tests/test_transform_joinaggregate.rs

Updates the sum aggregation function to return `null` when passed all null values instead of returning 0. This will match the coming behavior of Vega 5.26.2.
See https://github.com/vega/vega/pull/3849

Update sum([null]) aggregation to be null to match Vega 5.26.2

---

.github/workflows/build_test.yml
python/vegafusion/vegafusion/datasource/dfi_datasource.py

Version 1.6.0 inadvertently caused a hard dependency on pyarrow 11's dataframe interchange support.  This PR removes that hard dependency by delaying the import of dataframe interchange support until needed.

Restore pyarrow 10 support

---

vegafusion-core/src/planning/lift_facet_aggregations.rs
vegafusion-runtime/tests/specs/custom/facet_lift_area.comm_plan.json
vegafusion-runtime/tests/specs/custom/facet_lift_area.vg.json
vegafusion-runtime/tests/specs/custom/facet_lift_area_color.comm_plan.json
vegafusion-runtime/tests/specs/custom/facet_lift_area_color.vg.json
vegafusion-runtime/tests/test_image_comparison.rs

Enhances the facet aggregation lifting planner phase to also handle lifting formula and filter transforms.  In addition, transforms that span datasets will also be lifted as long as each dataset has only a single child.

Improve facet lifting to handle formula and filter transforms

---

vegafusion-core/src/planning/lift_facet_aggregations.rs

Follow-on to https://github.com/hex-inc/vegafusion/pull/446 that also lifts leading `timeunit` and `bin` transforms in addition to `formula` and `filter`.

Lift bin and timeunit transforms out of facets

---

vegafusion-core/src/planning/stringify_local_datetimes.rs
vegafusion-runtime/tests/specs/custom/local_timezone_with_dot.comm_plan.json
vegafusion-runtime/tests/specs/custom/local_timezone_with_dot.vg.json
vegafusion-runtime/tests/test_image_comparison.rs

The local datetime stringification planner step needs to unescape column names before constructing transforms

Fix local datetime stringification for columns that need escaping

---

.github/workflows/build_test.yml
vegafusion-core/src/planning/split_domain_data.rs
vegafusion-runtime/tests/specs/custom/gh_455.comm_plan.json
vegafusion-runtime/tests/specs/custom/gh_455.vg.json
vegafusion-runtime/tests/specs/custom/special_chars_bar.comm_plan.json
vegafusion-runtime/tests/specs/custom/special_chars_bar.vg.json

Support domain extraction for columns with escaped dots in their names

---

vegafusion-core/src/spec/transform/project.rs
vegafusion-runtime/tests/specs/custom/gh_456.comm_plan.json
vegafusion-runtime/tests/specs/custom/gh_456.vg.json
vegafusion-runtime/tests/test_image_comparison.rs

Fixes the planner's datetime stringification logic for columns that need escaping (like columns with dots in their names)

Fix datetime stringification with column names that need escaping

---

vegafusion-core/src/planning/projection_pushdown.rs
vegafusion-core/src/spec/transform/project.rs
vegafusion-runtime/tests/specs/custom/gh_456.comm_plan.json
vegafusion-runtime/tests/specs/custom/gh_456.vg.json
vegafusion-runtime/tests/test_image_comparison.rs

Handles detecting column usage for point selection datasets

Handle point selections in projection pushdown

---

vegafusion-core/src/spec/transform/aggregate.rs
vegafusion-core/src/spec/transform/fold.rs
vegafusion-core/src/spec/transform/pivot.rs
vegafusion-runtime/tests/specs/custom/facet_dots_sort_datum.comm_plan.json
vegafusion-runtime/tests/specs/custom/facet_dots_sort_datum.vg.json
vegafusion-runtime/tests/test_image_comparison.rs

Follow on to #459 that fixes handling of escaped fields in the local datetime stringification planner

Handle unescaping fields aggregate/fold/pivot in local datetime stringification planner step

---

vegafusion-core/src/planning/projection_pushdown.rs
vegafusion-runtime/tests/specs/custom/gh_463.comm_plan.json
vegafusion-runtime/tests/specs/custom/gh_463.vg.json
vegafusion-runtime/tests/test_image_comparison.rs

The issue reported in #463 is due to an error in dataset resolution in the projection pushdown planner. Essentially, projection pushdown was associating the columns used by the nested `data_0` dataset with those used by the top-level `data_0` dataset.

Fix parent scope resolution in projection pushdown optimization

---

python/vegafusion/tests/test_input_utc.py
vegafusion-core/src/planning/mod.rs
vegafusion-core/src/planning/plan.rs
vegafusion-core/src/planning/strip_encodings.rs
vegafusion-runtime/tests/test_planning.rs

In the course of doing some benchmarking of pan and zoom on large scatterplots, I found that the `description` encoding that Vega-Lite adds by default has a significant performance penalty.
Here are some chrome profile flamegraphs for a 40k row version of the Vega-Lite pan/zoom example at https://vega.github.io/vega-lite/examples/selection_translate_scatterplot_drag.html
Default canvas renderer
With description and ariaRoleDescription encoding channels removed.
These encoding channels have no effect when used with the canvas renderer, which is what Vega-Altair uses.

Strip description encoding channel for improved render performance

---

python/vegafusion/tests/test_datasource.py
python/vegafusion/vegafusion/datasource/pandas_datasource.py

Closes #472 
This PR updates the PandasDatasource to handle pandas columns with mixed types that trigger a pyarrow error. In this case we fall back to reporting the column type as string, and then convert the column to string in `fetch` if it's requested.

Fix arrow type inference error (fall back to string)

---

.github/workflows/build_test.yml
python/vegafusion/tests/test_pretransform.py
python/vegafusion/vegafusion/datasource/__init__.py
python/vegafusion/vegafusion/datasource/pyarrow_datasource.py
python/vegafusion/vegafusion/runtime.py

This PR was motivated by https://github.com/altair-viz/altair/issues/3280. This same PyArrow cropped up when using VegaFusion with a Polars DataFrame containing a Date32 column.  This PR adds a simple PyArrowDatasource that bypasses the DataFrame Interchange protocol, and this Date32 error. Then it converts Polars to PyArrow and uses this data source. The Polars docs say this is mostly a zero-cost conversion.

Support Date32 type with Polars

---

vegafusion-datafusion-udfs/src/udfs/datetime/date_to_utc_timestamp.rs
vegafusion-datafusion-udfs/src/udfs/datetime/str_to_utc_timestamp.rs
vegafusion-datafusion-udfs/src/udfs/datetime/timeunit.rs
vegafusion-datafusion-udfs/src/udfs/datetime/to_utc_timestamp.rs

The PR removes some panics that could happen in datetime conversions. In particular, we were using arrow's `unary` function to map a custom function across the elements of an arrow array. For performance reasons, the function will be run on the underlying arrow memory even when the corresponding element is `null`, so the function must be valid for any possible value of the type. For the Date/timestamp types, this causes problems because not all valid integers represent value Dates or Timestamps.  This PR switches to using the `try_unary` function which only evaluates the input function on non-null elements. In addition, I removed a bunch of `unwrap` with proper error propagation.

Fix panics for out-of-range timestamps

---

vegafusion-server/Cargo.toml

To allow [Crates.io](https://crates.io/) , [lib.rs](https://lib.rs/) and the [Rust Digger](https://rust-digger.code-maven.com/) to link to it. See [the manifest](https://doc.rust-lang.org/cargo/reference/manifest.html#the-repository-field) for the explanation.

It is better to use the repository field

---

vegafusion-core/src/planning/projection_pushdown.rs
vegafusion-core/src/spec/mark.rs
vegafusion-runtime/tests/specs/custom/offset_inside_x.comm_plan.json
vegafusion-runtime/tests/specs/custom/offset_inside_x.vg.json
vegafusion-runtime/tests/test_image_comparison.rs

Fix projection pushdown to detect column usage inside the `offset` encoding inside a parent position encoding. For example:
```json
"x": {
"value": 0,
"offset": {
"scale": "x", "field": "Horsepower"
}
}
```
I don't see documentation for this in https://vega.github.io/vega-lite/docs/encoding.html#position, but Vega-Lite produces it sometimes.

Fix projection pushdown with offset encodings

---

pixi.lock
pixi.toml
vegafusion-core/src/planning/projection_pushdown.rs
vegafusion-core/src/spec/data.rs
vegafusion-python/src/lib.rs
vegafusion-python/tests/test_get_column_usage.py
vegafusion-python/vegafusion/__init__.py
vegafusion-python/vegafusion/utils.py
vegafusion-runtime/tests/test_projection_pushdown.rs

Adds a `get_column_usage` utility function for Rust and Python that compute the columns from the root datasets that are used by a Vega spec.
I'm planning to remove the Python Datasource logic in favor of projecting down to the required columns and then using the Arrow PyCapsule API.  This should be more efficient as it won't involve calling back into Python to load data.

Add get_column_usage utility function

---

.github/workflows/build_test.yml
Cargo.lock
Cargo.toml
vegafusion-core/Cargo.toml
vegafusion-datafusion-udfs/Cargo.toml
vegafusion-python/Cargo.toml
vegafusion-python/checks/check_lazy_imports.py
vegafusion-python/pyproject.toml
vegafusion-python/ruff.toml
vegafusion-python/src/lib.rs
vegafusion-python/vegafusion/runtime.py
vegafusion-runtime/Cargo.toml
vegafusion-sql/Cargo.toml

This PR drops the hard dependencies on pandas and pyarrow, and adds a test that using Altair+VegaFusion with polars does not trigger an import of pandas or pyarrow.
I also removed the psutil dependency by implementing the system lookup info in rust using the [`sysinfo`](https://docs.rs/sysinfo/latest/sysinfo/) crate.  Now the `vegafusion` Python library has only three dependencies.
- `narwhals` for abstracting over DataFrames (185.3 kB wheel, pure Python)
- `arro3-core` for basic Arrow processing in Python (2-4MB, compiled with wheels available for more platforms that VegaFusion currently builds for. In contrast, the `pyarrow` wheel sizes vary across platforms from 25MB to 40MB).
- `packaging` for the `Version` object (54.0 kB wheel, pure Python)
`narwhals` and `packaging` are also …

Trim Python dependencies

---

vegafusion-python/vegafusion/runtime.py

Hey, this does a couple of things:
- refactors the loop to use expressions, as that'll make the most out of backends like Polars (which, even with eager dataframes, can perform some optimisations when you use expressions as opposed to Series)
- uses the `narwhals.stable.v1` api (see https://github.com/vega/altair/pull/3670 for an example of where it ended up being really useful)

perf: use Narwhals expressions (and stable API)

---

.github/workflows/README.md
.github/workflows/build_test.yml
Cargo.lock
README.md
automation/bump_version.py
vegafusion-common/Cargo.toml
vegafusion-core/Cargo.toml
vegafusion-python/Cargo.toml
vegafusion-python/pyproject.toml
vegafusion-python/vegafusion/__init__.py
vegafusion-runtime/Cargo.toml
vegafusion-server/Cargo.toml
vegafusion-wasm/Cargo.toml
vegafusion-wasm/package-lock.json
vegafusion-wasm/package.json

- Update GitHub actions to remove deprecations
- Bump version to 2.0.0a0
- Add empty embed group for backward compatibility
- Use release-opt profile consistently for CI artifacts

v2-chore: Cleanup toward v2 release

---

RELEASE.md
docs/source/conf.py
docs/source/index.md
docs/source/posts/2022/2022-01-19_Release_0.0.1.md
docs/source/posts/2022/2022-01-27_ProjectAnnouncement.md
docs/source/posts/2023/2023-01-21_Release_1.0.0.md
docs/source/posts/2023/2023-03-25_Release_1.1.0.md
docs/source/posts/2023/2023-04-12_Release_1.2.0.md
docs/source/posts/2023/2023-06-10_Release_1.3.0.md
docs/source/posts/2023/2023-08-21_Release_1.4.0.md
docs/source/posts/2024/2024-11-13_Release_2.0.0.md
docs/source/posts/posts.md
docs/sync_docs.sh
pixi.toml

Updates the RELEASE.md for the new release artifacts, adds a sync_docs.sh script to push the docs to the gh-pages branch of https://github.com/vegafusion/vegafusion.github.io (currently under a v2 sub-directory, but after release this will be the root).

v2-docs: Update release instructions, add sync_docs script

---

Cargo.lock
RELEASE.md
docs/source/features/chart_state.md
docs/source/features/column_usage.md
docs/source/features/embed.md
docs/source/features/grpc.md
docs/source/features/inline_datasets.md
docs/source/features/transform_data.md
docs/source/features/transform_extract.md
docs/source/features/transform_spec.md
docs/sync_docs.sh
vegafusion-common/Cargo.toml
vegafusion-core/Cargo.toml
vegafusion-python/Cargo.toml
vegafusion-python/pyproject.toml
vegafusion-runtime/Cargo.toml
vegafusion-server/Cargo.toml
vegafusion-wasm/Cargo.toml
vegafusion-wasm/package-lock.json
vegafusion-wasm/package.json

Release branch for version 2.0.0

Release 2.0.0
