vega/vegafusion

- Cargo.lock
- vegafusion-core/src/planning/plan.rs
- vegafusion-core/src/planning/watch.rs
- vegafusion-core/src/spec/visitors.rs
- vegafusion-rt-datafusion/Cargo.toml
- vegafusion-rt-datafusion/benches/spec_benchmarks.rs
- vegafusion-rt-datafusion/benches/specs/flights_crossfilter.updates.json
- vegafusion-rt-datafusion/benches/specs/flights_crossfilter.vg.json
- vegafusion-rt-datafusion/benches/specs/flights_crossfilter_local_time.updates.json
- vegafusion-rt-datafusion/benches/specs/flights_crossfilter_local_time.vg.json
- vegafusion-rt-datafusion/tests/test_image_comparison.rs
- vegafusion-rt-datafusion/tests/util/vegajs_runtime/mod.rs
And two initial criterion benchmarks
> Add initial benchmark

- vegafusion-core/src/spec/transform/aggregate.rs
- vegafusion-core/src/spec/transform/joinaggregate.rs
- vegafusion-rt-datafusion/src/transform/aggregate.rs
- vegafusion-rt-datafusion/src/transform/joinaggregate.rs
- vegafusion-rt-datafusion/tests/specs/custom/movies_agg_parameterize.comm_plan.json
- vegafusion-rt-datafusion/tests/specs/custom/movies_agg_parameterize.vg.json
- vegafusion-rt-datafusion/tests/specs/vegalite/layer_point_errorbar_2d_horizontal_stdev.comm_plan.json
- vegafusion-rt-datafusion/tests/specs/vegalite/layer_point_errorbar_stdev.comm_plan.json
- vegafusion-rt-datafusion/tests/specs/vegalite/layer_scatter_errorband_1D_stdev_global_mean.comm_plan.json
- vegafusion-rt-datafusion/tests/specs/vegalite/layer_scatter_errorband_1d_stdev.comm_plan.json
- vegafusion-rt-datafusion/tests/test_image_comparison.rs
Adds support for additional `aggregate` operations: variance, variancep, stdev, and stdevp
> Add variance, variancep, stdev, and stdevp aggregate operations

- Cargo.lock
- vegafusion-core/Cargo.toml
- vegafusion-core/src/data/scalar.rs
- vegafusion-core/src/data/table.rs
- vegafusion-rt-datafusion/Cargo.toml
- vegafusion-rt-datafusion/src/expression/compiler/builtin_functions/data/vl_selection_resolve.rs
- vegafusion-rt-datafusion/src/expression/compiler/builtin_functions/data/vl_selection_test.rs
- vegafusion-rt-datafusion/src/expression/compiler/mod.rs
- vegafusion-rt-datafusion/src/expression/compiler/utils.rs
- vegafusion-rt-datafusion/src/transform/bin.rs
- vegafusion-rt-datafusion/src/transform/extent.rs
- vegafusion-rt-datafusion/src/transform/joinaggregate.rs
- vegafusion-rt-datafusion/tests/test_vegajs_runtime.rs
Update DataFusion dependency to hash [0ff59de810f344b197b2e9491a0a9aefca52d88f](https://github.com/apache/arrow-datafusion/commit/0ff59de810f344b197b2e9491a0a9aefca52d88f).
> Update DataFusion to latest master hash (0ff59d)

- vegafusion-core/src/planning/stringify_local_datetimes.rs
- vegafusion-rt-datafusion/tests/test_stringify_datetimes.rs
Closes https://github.com/vegafusion/vegafusion/issues/130
> Fix stringify local datetimes planner for Safari

- BUILD.md
As I was going through the setup steps to be able to run VegaFusion tests, I had to run a few more commands in order to get things to work. Not sure that all the changes I've made to the steps are completely accurate/necessary, but I believe they should at least be a net improvement. Feel free to make edits to this PR as desired!
> A few BUILD.md tweaks

- .github/workflows/build_test.yml
- Cargo.lock
- javascript/vegafusion-embed/package-lock.json
- python/vegafusion-jupyter/package-lock.json
- python/vegafusion-jupyter/tests/test_altair_mocks.py
- vegafusion-core/Cargo.toml
- vegafusion-core/src/data/json_writer.rs
- vegafusion-core/src/data/scalar.rs
- vegafusion-core/src/data/table.rs
- vegafusion-core/src/task_graph/memory.rs
- vegafusion-rt-datafusion/Cargo.toml
- vegafusion-rt-datafusion/src/expression/compiler/array.rs
- vegafusion-rt-datafusion/src/expression/compiler/builtin_functions/array/length.rs
- vegafusion-rt-datafusion/src/expression/compiler/builtin_functions/array/span.rs
- vegafusion-rt-datafusion/src/expression/compiler/builtin_functions/data/vl_selection_resolve.rs
- vegafusion-rt-datafusion/src/expression/compiler/builtin_functions/date_time/date_parts.rs
- vegafusion-rt-datafusion/src/expression/compiler/builtin_functions/date_time/datetime.rs
- vegafusion-rt-datafusion/src/expression/compiler/member.rs
- vegafusion-rt-datafusion/src/expression/compiler/mod.rs
- vegafusion-rt-datafusion/src/transform/bin.rs
- vegafusion-rt-datafusion/src/transform/extent.rs
- vegafusion-rt-datafusion/src/transform/impute.rs
- vegafusion-rt-datafusion/tests/specs/custom/bug_153.comm_plan.json
- vegafusion-rt-datafusion/tests/specs/custom/bug_153.vg.json
- vegafusion-rt-datafusion/tests/test_image_comparison.rs
- vegafusion-rt-datafusion/tests/test_vegajs_runtime.rs
Closes #153 
This PR adds an initially failing test based on #153, then updates the DataFusion dependency to include the fix from https://github.com/apache/arrow-datafusion/pull/2968, which makes the test pass.
> Fix crash when coloring by string column

- vegafusion-core/src/proto/prost_gen/transforms.rs
- vegafusion-core/src/proto/tonic_gen/transforms.rs
- vegafusion-core/src/proto/transforms.proto
- vegafusion-core/src/spec/transform/identifier.rs
- vegafusion-core/src/spec/transform/mod.rs
- vegafusion-core/src/spec/transform/unsupported.rs
- vegafusion-core/src/transform/identifier.rs
- vegafusion-core/src/transform/mod.rs
- vegafusion-rt-datafusion/src/transform/identifier.rs
- vegafusion-rt-datafusion/src/transform/mod.rs
- vegafusion-rt-datafusion/tests/specs/vegalite/concat_hover.comm_plan.json
- vegafusion-rt-datafusion/tests/specs/vegalite/concat_hover_filter.comm_plan.json
- vegafusion-rt-datafusion/tests/specs/vegalite/interactive_multi_line_tooltip.comm_plan.json
- vegafusion-rt-datafusion/tests/specs/vegalite/interactive_paintbrush.comm_plan.json
- vegafusion-rt-datafusion/tests/specs/vegalite/interactive_paintbrush_color.comm_plan.json
- vegafusion-rt-datafusion/tests/specs/vegalite/interactive_paintbrush_color_nearest.comm_plan.json
- vegafusion-rt-datafusion/tests/specs/vegalite/interactive_paintbrush_simple_false.comm_plan.json
- vegafusion-rt-datafusion/tests/specs/vegalite/interactive_paintbrush_simple_true.comm_plan.json
- vegafusion-rt-datafusion/tests/specs/vegalite/selection_insert.comm_plan.json
- vegafusion-rt-datafusion/tests/specs/vegalite/selection_multi_condition.comm_plan.json
- vegafusion-rt-datafusion/tests/specs/vegalite/selection_project_multi.comm_plan.json
- vegafusion-rt-datafusion/tests/specs/vegalite/selection_project_single.comm_plan.json
- vegafusion-rt-datafusion/tests/specs/vegalite/selection_toggle_altKey.comm_plan.json
- vegafusion-rt-datafusion/tests/specs/vegalite/selection_toggle_altKey_shiftKey.comm_plan.json
- vegafusion-rt-datafusion/tests/specs/vegalite/selection_toggle_shiftKey.comm_plan.json
- vegafusion-rt-datafusion/tests/specs/vegalite/selection_type_point.comm_plan.json
- vegafusion-rt-datafusion/tests/specs/vegalite/selection_type_single_dblclick.comm_plan.json
- vegafusion-rt-datafusion/tests/specs/vegalite/selection_type_single_mouseover.comm_plan.json
- vegafusion-rt-datafusion/tests/test_transform_identifier.rs
This PR adds support for the Vega [`identifier`](https://vega.github.io/vega/docs/transforms/identifier/) transform.
Closes https://github.com/vegafusion/vegafusion/issues/170
> Add identifier transform

- vegafusion-core/src/spec/data.rs
- vegafusion-rt-datafusion/tests/specs/pre_transform/empty_store_array.vg.json
- vegafusion-rt-datafusion/tests/test_pre_transform_values.rs
> Allow empty values arrays on the server in pre_transform_spec

- Cargo.lock
- vegafusion-core/src/expression/supported.rs
- vegafusion-core/src/expression/visitors.rs
- vegafusion-rt-datafusion/Cargo.toml
- vegafusion-rt-datafusion/src/expression/compiler/builtin_functions/array/indexof.rs
- vegafusion-rt-datafusion/src/expression/compiler/builtin_functions/array/mod.rs
- vegafusion-rt-datafusion/src/expression/compiler/call.rs
- vegafusion-rt-datafusion/src/sql/connection/datafusion_conn.rs
- vegafusion-rt-datafusion/tests/specs/vegalite/layer_ranged_dot.comm_plan.json
- vegafusion-rt-datafusion/tests/test_expression_evaluation.rs
- vegafusion-rt-datafusion/tests/test_transform_formula.rs
> Add support for indexof expression function

- python/vegafusion/vegafusion/local_tz.py
See https://github.com/vega/vl-convert/pull/38
> Fall back to "UTC" if get_local_tz() returns None

- README.md
Includes new quickstart examples for 1.0
> Add new 1.0 quickstart examples to the README.md

- vegafusion-core/src/expression/visitors.rs
- vegafusion-core/src/spec/transform/formula.rs
- vegafusion-runtime/tests/specs/custom/periods_in_formula_output.comm_plan.json
- vegafusion-runtime/tests/specs/custom/periods_in_formula_output.vg.json
- vegafusion-runtime/tests/specs/custom/special_chars_bar.comm_plan.json
- vegafusion-runtime/tests/test_image_comparison.rs
This removes a restriction on the formula transform that I put in early in VegaFusion's development, to prohibit it from outputting fields with periods in their names.
I seem to recall that I thought there was some special behavior here around creating nested object properties (which VegaFusion doesn't support), but I don't see any documentation for in in the Vega [formula transform](https://vega.github.io/vega/docs/transforms/formula/), and Vega seems to simply output a column name with a period in it. See:
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQgpAE84AJzQBtUABMkmFKlCykCOGhA4ksgxAD6BowDMN5y0uJJBDOBB1QAFkAeQA5ABUACUpQyKirACYABkSAZn5kgEZMrIACZOTUQuLkxRA46IdKhPQU9 …
> Support names with periods in formula output field

- python/vegafusion/tests/test_pretransform.py
- vegafusion-runtime/src/transform/timeunit.rs
Fix to support Arrow `Date32` and `Date64` columns in the timeunit transform. This is only an issue for the DuckDB connection as the DataFusion connection converts these to `Timestamp` columns on import.
> Support Date32 and Date64 in timeunit transform

- python/vegafusion/vegafusion/connection/duckdb.py
If accepting an external connection, don't change it
> Only set DuckDB pandas_analyze_sample when creating connection internally

- vegafusion-core/build.rs
Closes #324
Thanks for the suggestion @alexkreidler!
> Add --experimental_allow_proto3_optional protoc flag to tonic build

- python/vegafusion/vegafusion/connection/__init__.py
- python/vegafusion/vegafusion/connection/duckdb.py
- vegafusion-dataframe/src/connection.rs
- vegafusion-python-embed/src/connection.rs
- vegafusion-runtime/src/data/tasks.rs
- vegafusion-sql/src/connection/datafusion_conn.rs
> Refactor read arrow more efficiently and handle data format type specification

- BUILD.md
Updates to the build/test instructions
> Update build instructions for running tests

- vegafusion-common/src/data/json_writer.rs
- vegafusion-datafusion-udfs/src/udfs/array/span.rs
- vegafusion-datafusion-udfs/src/udfs/datetime/mod.rs
- vegafusion-datafusion-udfs/src/udfs/datetime/timeunit.rs
- vegafusion-datafusion-udfs/src/udfs/datetime/to_utc_timestamp.rs
- vegafusion-runtime/src/data/tasks.rs
- vegafusion-runtime/src/task_graph/runtime.rs
- vegafusion-runtime/src/transform/aggregate.rs
- vegafusion-runtime/src/transform/pivot.rs
- vegafusion-runtime/src/transform/window.rs
- vegafusion-wasm/src/lib.rs
Removes a variety of panics from non-testing code
> Remove some panics

- python/vegafusion/tests/test_pretransform.py
- python/vegafusion/vegafusion/runtime.py
Defaults the `local_tz` argument to the `vf.runtime.pre_transform_*` functions to `vf.get_local_tz()`.
> Default local_tz to get_local_tz() in vf.runtime functions

- .github/workflows/build_test.yml
- vegafusion-python-embed/Cargo.toml
- vegafusion-python-embed/pyproject.toml
Closes https://github.com/hex-inc/vegafusion/issues/348 if it works!
> Build abi3 wheels so we don't need to build separate wheels for each platform

- Cargo.lock
- pixi.lock
- pixi.toml
Updates Rust to 1.72.0
Now that we're using pixi to manage the development environment, Rust updates are managed by pixi.
> Rust 1.72.0

- vegafusion-core/src/patch.rs
Closes https://github.com/hex-inc/vegafusion/issues/405
I went a bit conservative and updating patching to fail if there are any changes to datasets (including the adding or removing of full datasets or properties inside datasets).
> Make patching fail if there are changes to any dataset

- .github/workflows/build_test.yml
- .github/workflows/java.yml
- vegafusion-sql/Cargo.toml
- vegafusion-sql/src/compile/scalar.rs
- vegafusion-sql/src/dialect/mod.rs
- vegafusion-sql/src/dialect/transforms/epoch_ms_to_utc_timestamp.rs
- vegafusion-sql/src/dialect/transforms/to_utc_timestamp.rs
- vegafusion-sql/tests/expected/select.toml
- vegafusion-sql/tests/test_select.rs
Adds support for the `to_utc_timestamp` function in Snowflake, BigQuery, and Databricks SQL dialects
> Add to_utc_timestamp support in more dialects

- python/vegafusion/vegafusion/transformer.py
- vegafusion-core/src/planning/dependency_graph.rs
- vegafusion-core/src/planning/fuse.rs
- vegafusion-core/src/planning/lift_facet_aggregations.rs
- vegafusion-python-embed/src/lib.rs
- vegafusion-runtime/src/data/tasks.rs
- vegafusion-runtime/src/task_graph/runtime.rs
- vegafusion-sql/src/connection/datafusion_conn.rs
Small updates in preparation for integrating ChartState into Altair's JupyterChart
Also some formatting updates
> ChartState Updats

- vegafusion-python-embed/src/connection.rs
Adds parquet support to the DuckDB connection. The DataFusion connection already has parquet support
> Add parquet support for DuckDB connection

- pixi.lock
- pixi.toml
- python/vegafusion/tests/test_conext_manager.py
- python/vegafusion/vegafusion/__init__.py
- vegafusion-runtime/tests/test_image_comparison.rs
Closes https://github.com/vega/vegafusion/issues/474
> Don't set Altair's embed_options to None

- pixi.lock
- pixi.toml
- vegafusion-runtime/src/data/tasks.rs
- vegafusion-runtime/src/transform/pipeline.rs
- vegafusion-runtime/tests/test_pre_transform_values.rs
- vegafusion-runtime/tests/util/check.rs
We were handling `parse` of `date:'%Y'`, but not `date:%Y`.
> Fix custom date format parse

- .github/workflows/build_test.yml
- Cargo.lock
- pixi.lock
- pixi.toml
- vegafusion-common/Cargo.toml
- vegafusion-core/Cargo.toml
- vegafusion-python/Cargo.toml
- vegafusion-python/pyproject.toml
- vegafusion-runtime/Cargo.toml
- vegafusion-server/Cargo.toml
- vegafusion-wasm/Cargo.toml
- vegafusion-wasm/package-lock.json
- vegafusion-wasm/package.json
Release branch for 2.0.1 with date format parsing fix from https://github.com/vega/vegafusion/pull/551
Also trying to address https://github.com/vega/vegafusion/issues/553, as i think it's an issue with the sdist files overlapping each other on download.
> Release 2.0.1

- docs/source/posts/2024/2024-11-13_Release_2.0.0.md
Social media driven development https://www.linkedin.com/feed/update/urn:li:activity:7266923717383933956?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A7266923717383933956%2C7266927618703204352%29&dashCommentUrn=urn%3Ali%3Afsd_comment%3A%287266927618703204352%2Curn%3Ali%3Aactivity%3A7266923717383933956%29 
😄
> fix typo in Vegafusion 2.0 release notes title

- Cargo.lock
- vegafusion-common/Cargo.toml
- vegafusion-core/Cargo.toml
- vegafusion-python/Cargo.toml
- vegafusion-python/pyproject.toml
- vegafusion-runtime/Cargo.toml
- vegafusion-server/Cargo.toml
- vegafusion-wasm/Cargo.toml
- vegafusion-wasm/package-lock.json
- vegafusion-wasm/package.json
> Relase 2.0.2

- .claude/settings.local.json
- Cargo.lock
- vegafusion-common/Cargo.toml
- vegafusion-core/Cargo.toml
- vegafusion-core/src/expression/lexer.rs
- vegafusion-python/Cargo.toml
- vegafusion-python/pyproject.toml
- vegafusion-python/vegafusion/runtime.py
- vegafusion-runtime/Cargo.toml
- vegafusion-runtime/src/transform/window.rs
- vegafusion-server/Cargo.toml
- vegafusion-wasm/Cargo.toml
- vegafusion-wasm/package-lock.json
- vegafusion-wasm/package.json
Release branch for 2.0.3. Includes fix for https://github.com/vega/vegafusion/issues/569 and dependency updates
> Release 2.0.3
